"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _CompassMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CompassModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CompassMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DYNAMIC: _CompassMode.ValueType  # 0
    """
    Compass with dynamic ring and heading
    """
    FIXED_RING: _CompassMode.ValueType  # 1
    """
    Compass with fixed ring and heading
    """
    FREEZE_HEADING: _CompassMode.ValueType  # 2
    """
    Compass with heading and freeze option
    """

class CompassMode(_CompassMode, metaclass=_CompassModeEnumTypeWrapper): ...

DYNAMIC: CompassMode.ValueType  # 0
"""
Compass with dynamic ring and heading
"""
FIXED_RING: CompassMode.ValueType  # 1
"""
Compass with fixed ring and heading
"""
FREEZE_HEADING: CompassMode.ValueType  # 2
"""
Compass with heading and freeze option
"""
Global___CompassMode: _TypeAlias = CompassMode  # noqa: Y015

class _Theme:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ThemeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Theme.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DARK: _Theme.ValueType  # 0
    """
    Dark
    """
    LIGHT: _Theme.ValueType  # 1
    """
    Light
    """
    RED: _Theme.ValueType  # 2
    """
    Red
    """

class Theme(_Theme, metaclass=_ThemeEnumTypeWrapper): ...

DARK: Theme.ValueType  # 0
"""
Dark
"""
LIGHT: Theme.ValueType  # 1
"""
Light
"""
RED: Theme.ValueType  # 2
"""
Red
"""
Global___Theme: _TypeAlias = Theme  # noqa: Y015

class _Language:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LanguageEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Language.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ENGLISH: _Language.ValueType  # 0
    """
    English
    """
    FRENCH: _Language.ValueType  # 1
    """
    French
    """
    GERMAN: _Language.ValueType  # 2
    """
    German
    """
    ITALIAN: _Language.ValueType  # 3
    """
    Italian
    """
    PORTUGUESE: _Language.ValueType  # 4
    """
    Portuguese
    """
    SPANISH: _Language.ValueType  # 5
    """
    Spanish
    """
    SWEDISH: _Language.ValueType  # 6
    """
    Swedish
    """
    FINNISH: _Language.ValueType  # 7
    """
    Finnish
    """
    POLISH: _Language.ValueType  # 8
    """
    Polish
    """
    TURKISH: _Language.ValueType  # 9
    """
    Turkish
    """
    SERBIAN: _Language.ValueType  # 10
    """
    Serbian
    """
    RUSSIAN: _Language.ValueType  # 11
    """
    Russian
    """
    DUTCH: _Language.ValueType  # 12
    """
    Dutch
    """
    GREEK: _Language.ValueType  # 13
    """
    Greek
    """
    NORWEGIAN: _Language.ValueType  # 14
    """
    Norwegian
    """
    SLOVENIAN: _Language.ValueType  # 15
    """
    Slovenian
    """
    UKRAINIAN: _Language.ValueType  # 16
    """
    Ukrainian
    """
    BULGARIAN: _Language.ValueType  # 17
    """
    Bulgarian
    """
    CZECH: _Language.ValueType  # 18
    """
    Czech
    """
    DANISH: _Language.ValueType  # 19
    """
    Danish
    """
    SIMPLIFIED_CHINESE: _Language.ValueType  # 30
    """
    Simplified Chinese (experimental)
    """
    TRADITIONAL_CHINESE: _Language.ValueType  # 31
    """
    Traditional Chinese (experimental)
    """

class Language(_Language, metaclass=_LanguageEnumTypeWrapper):
    """
    Localization
    """

ENGLISH: Language.ValueType  # 0
"""
English
"""
FRENCH: Language.ValueType  # 1
"""
French
"""
GERMAN: Language.ValueType  # 2
"""
German
"""
ITALIAN: Language.ValueType  # 3
"""
Italian
"""
PORTUGUESE: Language.ValueType  # 4
"""
Portuguese
"""
SPANISH: Language.ValueType  # 5
"""
Spanish
"""
SWEDISH: Language.ValueType  # 6
"""
Swedish
"""
FINNISH: Language.ValueType  # 7
"""
Finnish
"""
POLISH: Language.ValueType  # 8
"""
Polish
"""
TURKISH: Language.ValueType  # 9
"""
Turkish
"""
SERBIAN: Language.ValueType  # 10
"""
Serbian
"""
RUSSIAN: Language.ValueType  # 11
"""
Russian
"""
DUTCH: Language.ValueType  # 12
"""
Dutch
"""
GREEK: Language.ValueType  # 13
"""
Greek
"""
NORWEGIAN: Language.ValueType  # 14
"""
Norwegian
"""
SLOVENIAN: Language.ValueType  # 15
"""
Slovenian
"""
UKRAINIAN: Language.ValueType  # 16
"""
Ukrainian
"""
BULGARIAN: Language.ValueType  # 17
"""
Bulgarian
"""
CZECH: Language.ValueType  # 18
"""
Czech
"""
DANISH: Language.ValueType  # 19
"""
Danish
"""
SIMPLIFIED_CHINESE: Language.ValueType  # 30
"""
Simplified Chinese (experimental)
"""
TRADITIONAL_CHINESE: Language.ValueType  # 31
"""
Traditional Chinese (experimental)
"""
Global___Language: _TypeAlias = Language  # noqa: Y015

@_typing.final
class DeviceUIConfig(_message.Message):
    """
    Protobuf structures for device-ui persistency
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _GpsCoordinateFormat:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _GpsCoordinateFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceUIConfig._GpsCoordinateFormat.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEC: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 0
        """
        GPS coordinates are displayed in the normal decimal degrees format:
        DD.DDDDDD DDD.DDDDDD
        """
        DMS: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 1
        """
        GPS coordinates are displayed in the degrees minutes seconds format:
        DD°MM'SS"C DDD°MM'SS"C, where C is the compass point representing the locations quadrant
        """
        UTM: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 2
        """
        Universal Transverse Mercator format:
        ZZB EEEEEE NNNNNNN, where Z is zone, B is band, E is easting, N is northing
        """
        MGRS: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 3
        """
        Military Grid Reference System format:
        ZZB CD EEEEE NNNNN, where Z is zone, B is band, C is the east 100k square, D is the north 100k square,
        E is easting, N is northing
        """
        OLC: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 4
        """
        Open Location Code (aka Plus Codes).
        """
        OSGR: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 5
        """
        Ordnance Survey Grid Reference (the National Grid System of the UK).
        Format: AB EEEEE NNNNN, where A is the east 100k square, B is the north 100k square,
        E is the easting, N is the northing
        """
        MLS: DeviceUIConfig._GpsCoordinateFormat.ValueType  # 6
        """
        Maidenhead Locator System
        Described here: https://en.wikipedia.org/wiki/Maidenhead_Locator_System
        """

    class GpsCoordinateFormat(_GpsCoordinateFormat, metaclass=_GpsCoordinateFormatEnumTypeWrapper):
        """
        How the GPS coordinates are displayed on the OLED screen.
        """

    DEC: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 0
    """
    GPS coordinates are displayed in the normal decimal degrees format:
    DD.DDDDDD DDD.DDDDDD
    """
    DMS: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 1
    """
    GPS coordinates are displayed in the degrees minutes seconds format:
    DD°MM'SS"C DDD°MM'SS"C, where C is the compass point representing the locations quadrant
    """
    UTM: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 2
    """
    Universal Transverse Mercator format:
    ZZB EEEEEE NNNNNNN, where Z is zone, B is band, E is easting, N is northing
    """
    MGRS: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 3
    """
    Military Grid Reference System format:
    ZZB CD EEEEE NNNNN, where Z is zone, B is band, C is the east 100k square, D is the north 100k square,
    E is easting, N is northing
    """
    OLC: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 4
    """
    Open Location Code (aka Plus Codes).
    """
    OSGR: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 5
    """
    Ordnance Survey Grid Reference (the National Grid System of the UK).
    Format: AB EEEEE NNNNN, where A is the east 100k square, B is the north 100k square,
    E is the easting, N is the northing
    """
    MLS: DeviceUIConfig.GpsCoordinateFormat.ValueType  # 6
    """
    Maidenhead Locator System
    Described here: https://en.wikipedia.org/wiki/Maidenhead_Locator_System
    """

    VERSION_FIELD_NUMBER: _builtins.int
    SCREEN_BRIGHTNESS_FIELD_NUMBER: _builtins.int
    SCREEN_TIMEOUT_FIELD_NUMBER: _builtins.int
    SCREEN_LOCK_FIELD_NUMBER: _builtins.int
    SETTINGS_LOCK_FIELD_NUMBER: _builtins.int
    PIN_CODE_FIELD_NUMBER: _builtins.int
    THEME_FIELD_NUMBER: _builtins.int
    ALERT_ENABLED_FIELD_NUMBER: _builtins.int
    BANNER_ENABLED_FIELD_NUMBER: _builtins.int
    RING_TONE_ID_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    NODE_FILTER_FIELD_NUMBER: _builtins.int
    NODE_HIGHLIGHT_FIELD_NUMBER: _builtins.int
    CALIBRATION_DATA_FIELD_NUMBER: _builtins.int
    MAP_DATA_FIELD_NUMBER: _builtins.int
    COMPASS_MODE_FIELD_NUMBER: _builtins.int
    SCREEN_RGB_COLOR_FIELD_NUMBER: _builtins.int
    IS_CLOCKFACE_ANALOG_FIELD_NUMBER: _builtins.int
    GPS_FORMAT_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate saved files when we make incompatible changes.
    """
    screen_brightness: _builtins.int
    """
    TFT display brightness 1..255
    """
    screen_timeout: _builtins.int
    """
    Screen timeout 0..900
    """
    screen_lock: _builtins.bool
    """
    Screen/Settings lock enabled
    """
    settings_lock: _builtins.bool
    pin_code: _builtins.int
    theme: Global___Theme.ValueType
    """
    Color theme
    """
    alert_enabled: _builtins.bool
    """
    Audible message, banner and ring tone
    """
    banner_enabled: _builtins.bool
    ring_tone_id: _builtins.int
    language: Global___Language.ValueType
    """
    Localization
    """
    calibration_data: _builtins.bytes
    """
    8 integers for screen calibration data
    """
    compass_mode: Global___CompassMode.ValueType
    """
    Compass mode
    """
    screen_rgb_color: _builtins.int
    """
    RGB color for BaseUI
    0xRRGGBB format, e.g. 0xFF0000 for red
    """
    is_clockface_analog: _builtins.bool
    """
    Clockface analog style
    true for analog clockface, false for digital clockface
    """
    gps_format: Global___DeviceUIConfig.GpsCoordinateFormat.ValueType
    """
    How the GPS coordinates are formatted on the OLED screen.
    """
    @_builtins.property
    def node_filter(self) -> Global___NodeFilter:
        """
        Node list filter
        """

    @_builtins.property
    def node_highlight(self) -> Global___NodeHighlight:
        """
        Node list highlightening
        """

    @_builtins.property
    def map_data(self) -> Global___Map:
        """
        Map related data
        """

    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        screen_brightness: _builtins.int = ...,
        screen_timeout: _builtins.int = ...,
        screen_lock: _builtins.bool = ...,
        settings_lock: _builtins.bool = ...,
        pin_code: _builtins.int = ...,
        theme: Global___Theme.ValueType = ...,
        alert_enabled: _builtins.bool = ...,
        banner_enabled: _builtins.bool = ...,
        ring_tone_id: _builtins.int = ...,
        language: Global___Language.ValueType = ...,
        node_filter: Global___NodeFilter | None = ...,
        node_highlight: Global___NodeHighlight | None = ...,
        calibration_data: _builtins.bytes = ...,
        map_data: Global___Map | None = ...,
        compass_mode: Global___CompassMode.ValueType = ...,
        screen_rgb_color: _builtins.int = ...,
        is_clockface_analog: _builtins.bool = ...,
        gps_format: Global___DeviceUIConfig.GpsCoordinateFormat.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["map_data", b"map_data", "node_filter", b"node_filter", "node_highlight", b"node_highlight"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alert_enabled", b"alert_enabled", "banner_enabled", b"banner_enabled", "calibration_data", b"calibration_data", "compass_mode", b"compass_mode", "gps_format", b"gps_format", "is_clockface_analog", b"is_clockface_analog", "language", b"language", "map_data", b"map_data", "node_filter", b"node_filter", "node_highlight", b"node_highlight", "pin_code", b"pin_code", "ring_tone_id", b"ring_tone_id", "screen_brightness", b"screen_brightness", "screen_lock", b"screen_lock", "screen_rgb_color", b"screen_rgb_color", "screen_timeout", b"screen_timeout", "settings_lock", b"settings_lock", "theme", b"theme", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceUIConfig: _TypeAlias = DeviceUIConfig  # noqa: Y015

@_typing.final
class NodeFilter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNKNOWN_SWITCH_FIELD_NUMBER: _builtins.int
    OFFLINE_SWITCH_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_SWITCH_FIELD_NUMBER: _builtins.int
    HOPS_AWAY_FIELD_NUMBER: _builtins.int
    POSITION_SWITCH_FIELD_NUMBER: _builtins.int
    NODE_NAME_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    unknown_switch: _builtins.bool
    """
    Filter unknown nodes
    """
    offline_switch: _builtins.bool
    """
    Filter offline nodes
    """
    public_key_switch: _builtins.bool
    """
    Filter nodes w/o public key
    """
    hops_away: _builtins.int
    """
    Filter based on hops away
    """
    position_switch: _builtins.bool
    """
    Filter nodes w/o position
    """
    node_name: _builtins.str
    """
    Filter nodes by matching name string
    """
    channel: _builtins.int
    """
    Filter based on channel
    """
    def __init__(
        self,
        *,
        unknown_switch: _builtins.bool = ...,
        offline_switch: _builtins.bool = ...,
        public_key_switch: _builtins.bool = ...,
        hops_away: _builtins.int = ...,
        position_switch: _builtins.bool = ...,
        node_name: _builtins.str = ...,
        channel: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "hops_away", b"hops_away", "node_name", b"node_name", "offline_switch", b"offline_switch", "position_switch", b"position_switch", "public_key_switch", b"public_key_switch", "unknown_switch", b"unknown_switch"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NodeFilter: _TypeAlias = NodeFilter  # noqa: Y015

@_typing.final
class NodeHighlight(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHAT_SWITCH_FIELD_NUMBER: _builtins.int
    POSITION_SWITCH_FIELD_NUMBER: _builtins.int
    TELEMETRY_SWITCH_FIELD_NUMBER: _builtins.int
    IAQ_SWITCH_FIELD_NUMBER: _builtins.int
    NODE_NAME_FIELD_NUMBER: _builtins.int
    chat_switch: _builtins.bool
    """
    Hightlight nodes w/ active chat
    """
    position_switch: _builtins.bool
    """
    Highlight nodes w/ position
    """
    telemetry_switch: _builtins.bool
    """
    Highlight nodes w/ telemetry data
    """
    iaq_switch: _builtins.bool
    """
    Highlight nodes w/ iaq data
    """
    node_name: _builtins.str
    """
    Highlight nodes by matching name string
    """
    def __init__(
        self,
        *,
        chat_switch: _builtins.bool = ...,
        position_switch: _builtins.bool = ...,
        telemetry_switch: _builtins.bool = ...,
        iaq_switch: _builtins.bool = ...,
        node_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chat_switch", b"chat_switch", "iaq_switch", b"iaq_switch", "node_name", b"node_name", "position_switch", b"position_switch", "telemetry_switch", b"telemetry_switch"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NodeHighlight: _TypeAlias = NodeHighlight  # noqa: Y015

@_typing.final
class GeoPoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ZOOM_FIELD_NUMBER: _builtins.int
    LATITUDE_FIELD_NUMBER: _builtins.int
    LONGITUDE_FIELD_NUMBER: _builtins.int
    zoom: _builtins.int
    """
    Zoom level
    """
    latitude: _builtins.int
    """
    Coordinate: latitude
    """
    longitude: _builtins.int
    """
    Coordinate: longitude
    """
    def __init__(
        self,
        *,
        zoom: _builtins.int = ...,
        latitude: _builtins.int = ...,
        longitude: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["latitude", b"latitude", "longitude", b"longitude", "zoom", b"zoom"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoPoint: _TypeAlias = GeoPoint  # noqa: Y015

@_typing.final
class Map(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOME_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    FOLLOW_GPS_FIELD_NUMBER: _builtins.int
    style: _builtins.str
    """
    Map tile style
    """
    follow_gps: _builtins.bool
    """
    Map scroll follows GPS
    """
    @_builtins.property
    def home(self) -> Global___GeoPoint:
        """
        Home coordinates
        """

    def __init__(
        self,
        *,
        home: Global___GeoPoint | None = ...,
        style: _builtins.str = ...,
        follow_gps: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["home", b"home"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["follow_gps", b"follow_gps", "home", b"home", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Map: _TypeAlias = Map  # noqa: Y015
