"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from meshtastic.aiomeshtastic.protobuf import channel_pb2 as _channel_pb2
from meshtastic.aiomeshtastic.protobuf import config_pb2 as _config_pb2
from meshtastic.aiomeshtastic.protobuf import localonly_pb2 as _localonly_pb2
from meshtastic.aiomeshtastic.protobuf import mesh_pb2 as _mesh_pb2
from meshtastic.aiomeshtastic.protobuf import telemetry_pb2 as _telemetry_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PositionLite(_message.Message):
    """
    Position with static location information only for NodeDBLite
    """

    DESCRIPTOR: _descriptor.Descriptor

    LATITUDE_I_FIELD_NUMBER: _builtins.int
    LONGITUDE_I_FIELD_NUMBER: _builtins.int
    ALTITUDE_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    LOCATION_SOURCE_FIELD_NUMBER: _builtins.int
    latitude_i: _builtins.int
    """
    The new preferred location encoding, multiply by 1e-7 to get degrees
    in floating point
    """
    longitude_i: _builtins.int
    """
    TODO: REPLACE
    """
    altitude: _builtins.int
    """
    In meters above MSL (but see issue #359)
    """
    time: _builtins.int
    """
    This is usually not sent over the mesh (to save space), but it is sent
    from the phone so that the local device can set its RTC If it is sent over
    the mesh (because there are devices on the mesh without GPS), it will only
    be sent by devices which has a hardware GPS clock.
    seconds since 1970
    """
    location_source: _mesh_pb2.Position.LocSource.ValueType
    """
    TODO: REPLACE
    """
    def __init__(
        self,
        *,
        latitude_i: _builtins.int = ...,
        longitude_i: _builtins.int = ...,
        altitude: _builtins.int = ...,
        time: _builtins.int = ...,
        location_source: _mesh_pb2.Position.LocSource.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["altitude", b"altitude", "latitude_i", b"latitude_i", "location_source", b"location_source", "longitude_i", b"longitude_i", "time", b"time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PositionLite: _TypeAlias = PositionLite  # noqa: Y015

@_typing.final
class UserLite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MACADDR_FIELD_NUMBER: _builtins.int
    LONG_NAME_FIELD_NUMBER: _builtins.int
    SHORT_NAME_FIELD_NUMBER: _builtins.int
    HW_MODEL_FIELD_NUMBER: _builtins.int
    IS_LICENSED_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    IS_UNMESSAGABLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def macaddr(self) -> _builtins.bytes:
        """
        This is the addr of the radio.
        """

    @macaddr.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def macaddr(self, value: _builtins.bytes) -> None:
        """
        This is the addr of the radio.
        """

    long_name: _builtins.str
    """
    A full name for this user, i.e. "Kevin Hester"
    """
    short_name: _builtins.str
    """
    A VERY short name, ideally two characters.
    Suitable for a tiny OLED screen
    """
    hw_model: _mesh_pb2.HardwareModel.ValueType
    """
    TBEAM, HELTEC, etc...
    Starting in 1.2.11 moved to hw_model enum in the NodeInfo object.
    Apps will still need the string here for older builds
    (so OTA update can find the right image), but if the enum is available it will be used instead.
    """
    is_licensed: _builtins.bool
    """
    In some regions Ham radio operators have different bandwidth limitations than others.
    If this user is a licensed operator, set this flag.
    Also, "long_name" should be their licence number.
    """
    role: _config_pb2.Config.DeviceConfig.Role.ValueType
    """
    Indicates that the user's role in the mesh
    """
    public_key: _builtins.bytes
    """
    The public key of the user's device.
    This is sent out to other nodes on the mesh to allow them to compute a shared secret key.
    """
    is_unmessagable: _builtins.bool
    """
    Whether or not the node can be messaged
    """
    def __init__(
        self,
        *,
        macaddr: _builtins.bytes = ...,
        long_name: _builtins.str = ...,
        short_name: _builtins.str = ...,
        hw_model: _mesh_pb2.HardwareModel.ValueType = ...,
        is_licensed: _builtins.bool = ...,
        role: _config_pb2.Config.DeviceConfig.Role.ValueType = ...,
        public_key: _builtins.bytes = ...,
        is_unmessagable: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_is_unmessagable", b"_is_unmessagable", "is_unmessagable", b"is_unmessagable"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_is_unmessagable", b"_is_unmessagable", "hw_model", b"hw_model", "is_licensed", b"is_licensed", "is_unmessagable", b"is_unmessagable", "long_name", b"long_name", "macaddr", b"macaddr", "public_key", b"public_key", "role", b"role", "short_name", b"short_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__is_unmessagable: _TypeAlias = _typing.Literal["is_unmessagable"]  # noqa: Y015
    _WhichOneofArgType__is_unmessagable: _TypeAlias = _typing.Literal["_is_unmessagable", b"_is_unmessagable"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_unmessagable) -> _WhichOneofReturnType__is_unmessagable | None: ...

Global___UserLite: _TypeAlias = UserLite  # noqa: Y015

@_typing.final
class NodeInfoLite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NUM_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    SNR_FIELD_NUMBER: _builtins.int
    LAST_HEARD_FIELD_NUMBER: _builtins.int
    DEVICE_METRICS_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    VIA_MQTT_FIELD_NUMBER: _builtins.int
    HOPS_AWAY_FIELD_NUMBER: _builtins.int
    IS_FAVORITE_FIELD_NUMBER: _builtins.int
    IS_IGNORED_FIELD_NUMBER: _builtins.int
    NEXT_HOP_FIELD_NUMBER: _builtins.int
    BITFIELD_FIELD_NUMBER: _builtins.int
    num: _builtins.int
    """
    The node number
    """
    snr: _builtins.float
    """
    Returns the Signal-to-noise ratio (SNR) of the last received message,
    as measured by the receiver. Return SNR of the last received message in dB
    """
    last_heard: _builtins.int
    """
    Set to indicate the last time we received a packet from this node
    """
    channel: _builtins.int
    """
    local channel index we heard that node on. Only populated if its not the default channel.
    """
    via_mqtt: _builtins.bool
    """
    True if we witnessed the node over MQTT instead of LoRA transport
    """
    hops_away: _builtins.int
    """
    Number of hops away from us this node is (0 if direct neighbor)
    """
    is_favorite: _builtins.bool
    """
    True if node is in our favorites list
    Persists between NodeDB internal clean ups
    """
    is_ignored: _builtins.bool
    """
    True if node is in our ignored list
    Persists between NodeDB internal clean ups
    """
    next_hop: _builtins.int
    """
    Last byte of the node number of the node that should be used as the next hop to reach this node.
    """
    bitfield: _builtins.int
    """
    Bitfield for storing booleans.
    LSB 0 is_key_manually_verified
    LSB 1 is_muted
    """
    @_builtins.property
    def user(self) -> Global___UserLite:
        """
        The user info for this node
        """

    @_builtins.property
    def position(self) -> Global___PositionLite:
        """
        This position data. Note: before 1.2.14 we would also store the last time we've heard from this node in position.time, that is no longer true.
        Position.time now indicates the last time we received a POSITION from that node.
        """

    @_builtins.property
    def device_metrics(self) -> _telemetry_pb2.DeviceMetrics:
        """
        The latest device metrics for the node.
        """

    def __init__(
        self,
        *,
        num: _builtins.int = ...,
        user: Global___UserLite | None = ...,
        position: Global___PositionLite | None = ...,
        snr: _builtins.float = ...,
        last_heard: _builtins.int = ...,
        device_metrics: _telemetry_pb2.DeviceMetrics | None = ...,
        channel: _builtins.int = ...,
        via_mqtt: _builtins.bool = ...,
        hops_away: _builtins.int | None = ...,
        is_favorite: _builtins.bool = ...,
        is_ignored: _builtins.bool = ...,
        next_hop: _builtins.int = ...,
        bitfield: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_hops_away", b"_hops_away", "device_metrics", b"device_metrics", "hops_away", b"hops_away", "position", b"position", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_hops_away", b"_hops_away", "bitfield", b"bitfield", "channel", b"channel", "device_metrics", b"device_metrics", "hops_away", b"hops_away", "is_favorite", b"is_favorite", "is_ignored", b"is_ignored", "last_heard", b"last_heard", "next_hop", b"next_hop", "num", b"num", "position", b"position", "snr", b"snr", "user", b"user", "via_mqtt", b"via_mqtt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hops_away: _TypeAlias = _typing.Literal["hops_away"]  # noqa: Y015
    _WhichOneofArgType__hops_away: _TypeAlias = _typing.Literal["_hops_away", b"_hops_away"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hops_away) -> _WhichOneofReturnType__hops_away | None: ...

Global___NodeInfoLite: _TypeAlias = NodeInfoLite  # noqa: Y015

@_typing.final
class DeviceState(_message.Message):
    """
    This message is never sent over the wire, but it is used for serializing DB
    state to flash in the device code
    FIXME, since we write this each time we enter deep sleep (and have infinite
    flash) it would be better to use some sort of append only data structure for
    the receive queue and use the preferences store for the other stuff
    """

    DESCRIPTOR: _descriptor.Descriptor

    MY_NODE_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    RECEIVE_QUEUE_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    RX_TEXT_MESSAGE_FIELD_NUMBER: _builtins.int
    NO_SAVE_FIELD_NUMBER: _builtins.int
    DID_GPS_RESET_FIELD_NUMBER: _builtins.int
    RX_WAYPOINT_FIELD_NUMBER: _builtins.int
    NODE_REMOTE_HARDWARE_PINS_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def no_save(self) -> _builtins.bool:
        """
        Used only during development.
        Indicates developer is testing and changes should never be saved to flash.
        Deprecated in 2.3.1
        """

    @no_save.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def no_save(self, value: _builtins.bool) -> None:
        """
        Used only during development.
        Indicates developer is testing and changes should never be saved to flash.
        Deprecated in 2.3.1
        """

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def did_gps_reset(self) -> _builtins.bool:
        """
        Previously used to manage GPS factory resets.
        Deprecated in 2.5.23
        """

    @did_gps_reset.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def did_gps_reset(self, value: _builtins.bool) -> None:
        """
        Previously used to manage GPS factory resets.
        Deprecated in 2.5.23
        """

    @_builtins.property
    def my_node(self) -> _mesh_pb2.MyNodeInfo:
        """
        Read only settings/info about this node
        """

    @_builtins.property
    def owner(self) -> _mesh_pb2.User:
        """
        My owner info
        """

    @_builtins.property
    def receive_queue(self) -> _containers.RepeatedCompositeFieldContainer[_mesh_pb2.MeshPacket]:
        """
        Received packets saved for delivery to the phone
        """

    @_builtins.property
    def rx_text_message(self) -> _mesh_pb2.MeshPacket:
        """
        We keep the last received text message (only) stored in the device flash,
        so we can show it on the screen.
        Might be null
        """

    @_builtins.property
    def rx_waypoint(self) -> _mesh_pb2.MeshPacket:
        """
        We keep the last received waypoint stored in the device flash,
        so we can show it on the screen.
        Might be null
        """

    @_builtins.property
    def node_remote_hardware_pins(self) -> _containers.RepeatedCompositeFieldContainer[_mesh_pb2.NodeRemoteHardwarePin]:
        """
        The mesh's nodes with their available gpio pins for RemoteHardware module
        """

    def __init__(
        self,
        *,
        my_node: _mesh_pb2.MyNodeInfo | None = ...,
        owner: _mesh_pb2.User | None = ...,
        receive_queue: _abc.Iterable[_mesh_pb2.MeshPacket] | None = ...,
        version: _builtins.int = ...,
        rx_text_message: _mesh_pb2.MeshPacket | None = ...,
        no_save: _builtins.bool = ...,
        did_gps_reset: _builtins.bool = ...,
        rx_waypoint: _mesh_pb2.MeshPacket | None = ...,
        node_remote_hardware_pins: _abc.Iterable[_mesh_pb2.NodeRemoteHardwarePin] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["my_node", b"my_node", "owner", b"owner", "rx_text_message", b"rx_text_message", "rx_waypoint", b"rx_waypoint"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["did_gps_reset", b"did_gps_reset", "my_node", b"my_node", "no_save", b"no_save", "node_remote_hardware_pins", b"node_remote_hardware_pins", "owner", b"owner", "receive_queue", b"receive_queue", "rx_text_message", b"rx_text_message", "rx_waypoint", b"rx_waypoint", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceState: _TypeAlias = DeviceState  # noqa: Y015

@_typing.final
class NodeDatabase(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    NODES_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @_builtins.property
    def nodes(self) -> _containers.RepeatedCompositeFieldContainer[Global___NodeInfoLite]:
        """
        New lite version of NodeDB to decrease memory footprint
        """

    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        nodes: _abc.Iterable[Global___NodeInfoLite] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nodes", b"nodes", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NodeDatabase: _TypeAlias = NodeDatabase  # noqa: Y015

@_typing.final
class ChannelFile(_message.Message):
    """
    The on-disk saved channels
    """

    DESCRIPTOR: _descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @_builtins.property
    def channels(self) -> _containers.RepeatedCompositeFieldContainer[_channel_pb2.Channel]:
        """
        The channels our node knows about
        """

    def __init__(
        self,
        *,
        channels: _abc.Iterable[_channel_pb2.Channel] | None = ...,
        version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChannelFile: _TypeAlias = ChannelFile  # noqa: Y015

@_typing.final
class BackupPreferences(_message.Message):
    """
    The on-disk backup of the node's preferences
    """

    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    MODULE_CONFIG_FIELD_NUMBER: _builtins.int
    CHANNELS_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    The version of the backup
    """
    timestamp: _builtins.int
    """
    The timestamp of the backup (if node has time)
    """
    @_builtins.property
    def config(self) -> _localonly_pb2.LocalConfig:
        """
        The node's configuration
        """

    @_builtins.property
    def module_config(self) -> _localonly_pb2.LocalModuleConfig:
        """
        The node's module configuration
        """

    @_builtins.property
    def channels(self) -> Global___ChannelFile:
        """
        The node's channels
        """

    @_builtins.property
    def owner(self) -> _mesh_pb2.User:
        """
        The node's user (owner) information
        """

    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        timestamp: _builtins.int = ...,
        config: _localonly_pb2.LocalConfig | None = ...,
        module_config: _localonly_pb2.LocalModuleConfig | None = ...,
        channels: Global___ChannelFile | None = ...,
        owner: _mesh_pb2.User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "config", b"config", "module_config", b"module_config", "owner", b"owner"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "config", b"config", "module_config", b"module_config", "owner", b"owner", "timestamp", b"timestamp", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BackupPreferences: _TypeAlias = BackupPreferences  # noqa: Y015
