"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _MessageType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MessageTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MessageType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ACK: _MessageType.ValueType  # 0
    COLLECT_INTERVAL: _MessageType.ValueType  # 160
    """in ms"""
    BEEP_ON: _MessageType.ValueType  # 161
    """duration ms"""
    BEEP_OFF: _MessageType.ValueType  # 162
    """cancel prematurely"""
    SHUTDOWN: _MessageType.ValueType  # 163
    POWER_ON: _MessageType.ValueType  # 164
    SCD41_TEMP: _MessageType.ValueType  # 176
    SCD41_HUMIDITY: _MessageType.ValueType  # 177
    SCD41_CO2: _MessageType.ValueType  # 178
    AHT20_TEMP: _MessageType.ValueType  # 179
    AHT20_HUMIDITY: _MessageType.ValueType  # 180
    TVOC_INDEX: _MessageType.ValueType  # 181

class MessageType(_MessageType, metaclass=_MessageTypeEnumTypeWrapper):
    """encapsulate up to 1k of NMEA string data"""

ACK: MessageType.ValueType  # 0
COLLECT_INTERVAL: MessageType.ValueType  # 160
"""in ms"""
BEEP_ON: MessageType.ValueType  # 161
"""duration ms"""
BEEP_OFF: MessageType.ValueType  # 162
"""cancel prematurely"""
SHUTDOWN: MessageType.ValueType  # 163
POWER_ON: MessageType.ValueType  # 164
SCD41_TEMP: MessageType.ValueType  # 176
SCD41_HUMIDITY: MessageType.ValueType  # 177
SCD41_CO2: MessageType.ValueType  # 178
AHT20_TEMP: MessageType.ValueType  # 179
AHT20_HUMIDITY: MessageType.ValueType  # 180
TVOC_INDEX: MessageType.ValueType  # 181
Global___MessageType: _TypeAlias = MessageType  # noqa: Y015

@_typing.final
class SensorData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    FLOAT_VALUE_FIELD_NUMBER: _builtins.int
    UINT32_VALUE_FIELD_NUMBER: _builtins.int
    type: Global___MessageType.ValueType
    """The message type"""
    float_value: _builtins.float
    uint32_value: _builtins.int
    def __init__(
        self,
        *,
        type: Global___MessageType.ValueType = ...,
        float_value: _builtins.float = ...,
        uint32_value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "float_value", b"float_value", "uint32_value", b"uint32_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "float_value", b"float_value", "type", b"type", "uint32_value", b"uint32_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_data: _TypeAlias = _typing.Literal["float_value", "uint32_value"]  # noqa: Y015
    _WhichOneofArgType_data: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_data) -> _WhichOneofReturnType_data | None: ...

Global___SensorData: _TypeAlias = SensorData  # noqa: Y015

@_typing.final
class InterdeviceMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NMEA_FIELD_NUMBER: _builtins.int
    SENSOR_FIELD_NUMBER: _builtins.int
    nmea: _builtins.str
    @_builtins.property
    def sensor(self) -> Global___SensorData: ...
    def __init__(
        self,
        *,
        nmea: _builtins.str = ...,
        sensor: Global___SensorData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "nmea", b"nmea", "sensor", b"sensor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "nmea", b"nmea", "sensor", b"sensor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_data: _TypeAlias = _typing.Literal["nmea", "sensor"]  # noqa: Y015
    _WhichOneofArgType_data: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_data) -> _WhichOneofReturnType_data | None: ...

Global___InterdeviceMessage: _TypeAlias = InterdeviceMessage  # noqa: Y015
