"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from meshtastic.aiomeshtastic.protobuf import config_pb2 as _config_pb2
from meshtastic.aiomeshtastic.protobuf import module_config_pb2 as _module_config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LocalConfig(_message.Message):
    """
    Protobuf structures common to apponly.proto and deviceonly.proto
    This is never sent over the wire, only for local use
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    POWER_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    DISPLAY_FIELD_NUMBER: _builtins.int
    LORA_FIELD_NUMBER: _builtins.int
    BLUETOOTH_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    SECURITY_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @_builtins.property
    def device(self) -> _config_pb2.Config.DeviceConfig:
        """
        The part of the config that is specific to the Device
        """

    @_builtins.property
    def position(self) -> _config_pb2.Config.PositionConfig:
        """
        The part of the config that is specific to the GPS Position
        """

    @_builtins.property
    def power(self) -> _config_pb2.Config.PowerConfig:
        """
        The part of the config that is specific to the Power settings
        """

    @_builtins.property
    def network(self) -> _config_pb2.Config.NetworkConfig:
        """
        The part of the config that is specific to the Wifi Settings
        """

    @_builtins.property
    def display(self) -> _config_pb2.Config.DisplayConfig:
        """
        The part of the config that is specific to the Display
        """

    @_builtins.property
    def lora(self) -> _config_pb2.Config.LoRaConfig:
        """
        The part of the config that is specific to the Lora Radio
        """

    @_builtins.property
    def bluetooth(self) -> _config_pb2.Config.BluetoothConfig:
        """
        The part of the config that is specific to the Bluetooth settings
        """

    @_builtins.property
    def security(self) -> _config_pb2.Config.SecurityConfig:
        """
        The part of the config that is specific to Security settings
        """

    def __init__(
        self,
        *,
        device: _config_pb2.Config.DeviceConfig | None = ...,
        position: _config_pb2.Config.PositionConfig | None = ...,
        power: _config_pb2.Config.PowerConfig | None = ...,
        network: _config_pb2.Config.NetworkConfig | None = ...,
        display: _config_pb2.Config.DisplayConfig | None = ...,
        lora: _config_pb2.Config.LoRaConfig | None = ...,
        bluetooth: _config_pb2.Config.BluetoothConfig | None = ...,
        version: _builtins.int = ...,
        security: _config_pb2.Config.SecurityConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bluetooth", b"bluetooth", "device", b"device", "display", b"display", "lora", b"lora", "network", b"network", "position", b"position", "power", b"power", "security", b"security"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bluetooth", b"bluetooth", "device", b"device", "display", b"display", "lora", b"lora", "network", b"network", "position", b"position", "power", b"power", "security", b"security", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocalConfig: _TypeAlias = LocalConfig  # noqa: Y015

@_typing.final
class LocalModuleConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MQTT_FIELD_NUMBER: _builtins.int
    SERIAL_FIELD_NUMBER: _builtins.int
    EXTERNAL_NOTIFICATION_FIELD_NUMBER: _builtins.int
    STORE_FORWARD_FIELD_NUMBER: _builtins.int
    RANGE_TEST_FIELD_NUMBER: _builtins.int
    TELEMETRY_FIELD_NUMBER: _builtins.int
    CANNED_MESSAGE_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    REMOTE_HARDWARE_FIELD_NUMBER: _builtins.int
    NEIGHBOR_INFO_FIELD_NUMBER: _builtins.int
    AMBIENT_LIGHTING_FIELD_NUMBER: _builtins.int
    DETECTION_SENSOR_FIELD_NUMBER: _builtins.int
    PAXCOUNTER_FIELD_NUMBER: _builtins.int
    STATUSMESSAGE_FIELD_NUMBER: _builtins.int
    TRAFFIC_MANAGEMENT_FIELD_NUMBER: _builtins.int
    TAK_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @_builtins.property
    def mqtt(self) -> _module_config_pb2.ModuleConfig.MQTTConfig:
        """
        The part of the config that is specific to the MQTT module
        """

    @_builtins.property
    def serial(self) -> _module_config_pb2.ModuleConfig.SerialConfig:
        """
        The part of the config that is specific to the Serial module
        """

    @_builtins.property
    def external_notification(self) -> _module_config_pb2.ModuleConfig.ExternalNotificationConfig:
        """
        The part of the config that is specific to the ExternalNotification module
        """

    @_builtins.property
    def store_forward(self) -> _module_config_pb2.ModuleConfig.StoreForwardConfig:
        """
        The part of the config that is specific to the Store & Forward module
        """

    @_builtins.property
    def range_test(self) -> _module_config_pb2.ModuleConfig.RangeTestConfig:
        """
        The part of the config that is specific to the RangeTest module
        """

    @_builtins.property
    def telemetry(self) -> _module_config_pb2.ModuleConfig.TelemetryConfig:
        """
        The part of the config that is specific to the Telemetry module
        """

    @_builtins.property
    def canned_message(self) -> _module_config_pb2.ModuleConfig.CannedMessageConfig:
        """
        The part of the config that is specific to the Canned Message module
        """

    @_builtins.property
    def audio(self) -> _module_config_pb2.ModuleConfig.AudioConfig:
        """
        The part of the config that is specific to the Audio module
        """

    @_builtins.property
    def remote_hardware(self) -> _module_config_pb2.ModuleConfig.RemoteHardwareConfig:
        """
        The part of the config that is specific to the Remote Hardware module
        """

    @_builtins.property
    def neighbor_info(self) -> _module_config_pb2.ModuleConfig.NeighborInfoConfig:
        """
        The part of the config that is specific to the Neighbor Info module
        """

    @_builtins.property
    def ambient_lighting(self) -> _module_config_pb2.ModuleConfig.AmbientLightingConfig:
        """
        The part of the config that is specific to the Ambient Lighting module
        """

    @_builtins.property
    def detection_sensor(self) -> _module_config_pb2.ModuleConfig.DetectionSensorConfig:
        """
        The part of the config that is specific to the Detection Sensor module
        """

    @_builtins.property
    def paxcounter(self) -> _module_config_pb2.ModuleConfig.PaxcounterConfig:
        """
        Paxcounter Config
        """

    @_builtins.property
    def statusmessage(self) -> _module_config_pb2.ModuleConfig.StatusMessageConfig:
        """
        StatusMessage Config
        """

    @_builtins.property
    def traffic_management(self) -> _module_config_pb2.ModuleConfig.TrafficManagementConfig:
        """
        The part of the config that is specific to the Traffic Management module
        """

    @_builtins.property
    def tak(self) -> _module_config_pb2.ModuleConfig.TAKConfig:
        """
        TAK Config
        """

    def __init__(
        self,
        *,
        mqtt: _module_config_pb2.ModuleConfig.MQTTConfig | None = ...,
        serial: _module_config_pb2.ModuleConfig.SerialConfig | None = ...,
        external_notification: _module_config_pb2.ModuleConfig.ExternalNotificationConfig | None = ...,
        store_forward: _module_config_pb2.ModuleConfig.StoreForwardConfig | None = ...,
        range_test: _module_config_pb2.ModuleConfig.RangeTestConfig | None = ...,
        telemetry: _module_config_pb2.ModuleConfig.TelemetryConfig | None = ...,
        canned_message: _module_config_pb2.ModuleConfig.CannedMessageConfig | None = ...,
        audio: _module_config_pb2.ModuleConfig.AudioConfig | None = ...,
        remote_hardware: _module_config_pb2.ModuleConfig.RemoteHardwareConfig | None = ...,
        neighbor_info: _module_config_pb2.ModuleConfig.NeighborInfoConfig | None = ...,
        ambient_lighting: _module_config_pb2.ModuleConfig.AmbientLightingConfig | None = ...,
        detection_sensor: _module_config_pb2.ModuleConfig.DetectionSensorConfig | None = ...,
        paxcounter: _module_config_pb2.ModuleConfig.PaxcounterConfig | None = ...,
        statusmessage: _module_config_pb2.ModuleConfig.StatusMessageConfig | None = ...,
        traffic_management: _module_config_pb2.ModuleConfig.TrafficManagementConfig | None = ...,
        tak: _module_config_pb2.ModuleConfig.TAKConfig | None = ...,
        version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ambient_lighting", b"ambient_lighting", "audio", b"audio", "canned_message", b"canned_message", "detection_sensor", b"detection_sensor", "external_notification", b"external_notification", "mqtt", b"mqtt", "neighbor_info", b"neighbor_info", "paxcounter", b"paxcounter", "range_test", b"range_test", "remote_hardware", b"remote_hardware", "serial", b"serial", "statusmessage", b"statusmessage", "store_forward", b"store_forward", "tak", b"tak", "telemetry", b"telemetry", "traffic_management", b"traffic_management"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ambient_lighting", b"ambient_lighting", "audio", b"audio", "canned_message", b"canned_message", "detection_sensor", b"detection_sensor", "external_notification", b"external_notification", "mqtt", b"mqtt", "neighbor_info", b"neighbor_info", "paxcounter", b"paxcounter", "range_test", b"range_test", "remote_hardware", b"remote_hardware", "serial", b"serial", "statusmessage", b"statusmessage", "store_forward", b"store_forward", "tak", b"tak", "telemetry", b"telemetry", "traffic_management", b"traffic_management", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocalModuleConfig: _TypeAlias = LocalModuleConfig  # noqa: Y015
