"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StoreAndForward(_message.Message):
    """
    TODO: REPLACE
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _RequestResponse:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RequestResponseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StoreAndForward._RequestResponse.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSET: StoreAndForward._RequestResponse.ValueType  # 0
        """
        Unset/unused
        """
        ROUTER_ERROR: StoreAndForward._RequestResponse.ValueType  # 1
        """
        Router is an in error state.
        """
        ROUTER_HEARTBEAT: StoreAndForward._RequestResponse.ValueType  # 2
        """
        Router heartbeat
        """
        ROUTER_PING: StoreAndForward._RequestResponse.ValueType  # 3
        """
        Router has requested the client respond. This can work as a
        "are you there" message.
        """
        ROUTER_PONG: StoreAndForward._RequestResponse.ValueType  # 4
        """
        The response to a "Ping"
        """
        ROUTER_BUSY: StoreAndForward._RequestResponse.ValueType  # 5
        """
        Router is currently busy. Please try again later.
        """
        ROUTER_HISTORY: StoreAndForward._RequestResponse.ValueType  # 6
        """
        Router is responding to a request for history.
        """
        ROUTER_STATS: StoreAndForward._RequestResponse.ValueType  # 7
        """
        Router is responding to a request for stats.
        """
        ROUTER_TEXT_DIRECT: StoreAndForward._RequestResponse.ValueType  # 8
        """
        Router sends a text message from its history that was a direct message.
        """
        ROUTER_TEXT_BROADCAST: StoreAndForward._RequestResponse.ValueType  # 9
        """
        Router sends a text message from its history that was a broadcast.
        """
        CLIENT_ERROR: StoreAndForward._RequestResponse.ValueType  # 64
        """
        Client is an in error state.
        """
        CLIENT_HISTORY: StoreAndForward._RequestResponse.ValueType  # 65
        """
        Client has requested a replay from the router.
        """
        CLIENT_STATS: StoreAndForward._RequestResponse.ValueType  # 66
        """
        Client has requested stats from the router.
        """
        CLIENT_PING: StoreAndForward._RequestResponse.ValueType  # 67
        """
        Client has requested the router respond. This can work as a
        "are you there" message.
        """
        CLIENT_PONG: StoreAndForward._RequestResponse.ValueType  # 68
        """
        The response to a "Ping"
        """
        CLIENT_ABORT: StoreAndForward._RequestResponse.ValueType  # 106
        """
        Client has requested that the router abort processing the client's request
        """

    class RequestResponse(_RequestResponse, metaclass=_RequestResponseEnumTypeWrapper):
        """
        001 - 063 = From Router
        064 - 127 = From Client
        """

    UNSET: StoreAndForward.RequestResponse.ValueType  # 0
    """
    Unset/unused
    """
    ROUTER_ERROR: StoreAndForward.RequestResponse.ValueType  # 1
    """
    Router is an in error state.
    """
    ROUTER_HEARTBEAT: StoreAndForward.RequestResponse.ValueType  # 2
    """
    Router heartbeat
    """
    ROUTER_PING: StoreAndForward.RequestResponse.ValueType  # 3
    """
    Router has requested the client respond. This can work as a
    "are you there" message.
    """
    ROUTER_PONG: StoreAndForward.RequestResponse.ValueType  # 4
    """
    The response to a "Ping"
    """
    ROUTER_BUSY: StoreAndForward.RequestResponse.ValueType  # 5
    """
    Router is currently busy. Please try again later.
    """
    ROUTER_HISTORY: StoreAndForward.RequestResponse.ValueType  # 6
    """
    Router is responding to a request for history.
    """
    ROUTER_STATS: StoreAndForward.RequestResponse.ValueType  # 7
    """
    Router is responding to a request for stats.
    """
    ROUTER_TEXT_DIRECT: StoreAndForward.RequestResponse.ValueType  # 8
    """
    Router sends a text message from its history that was a direct message.
    """
    ROUTER_TEXT_BROADCAST: StoreAndForward.RequestResponse.ValueType  # 9
    """
    Router sends a text message from its history that was a broadcast.
    """
    CLIENT_ERROR: StoreAndForward.RequestResponse.ValueType  # 64
    """
    Client is an in error state.
    """
    CLIENT_HISTORY: StoreAndForward.RequestResponse.ValueType  # 65
    """
    Client has requested a replay from the router.
    """
    CLIENT_STATS: StoreAndForward.RequestResponse.ValueType  # 66
    """
    Client has requested stats from the router.
    """
    CLIENT_PING: StoreAndForward.RequestResponse.ValueType  # 67
    """
    Client has requested the router respond. This can work as a
    "are you there" message.
    """
    CLIENT_PONG: StoreAndForward.RequestResponse.ValueType  # 68
    """
    The response to a "Ping"
    """
    CLIENT_ABORT: StoreAndForward.RequestResponse.ValueType  # 106
    """
    Client has requested that the router abort processing the client's request
    """

    @_typing.final
    class Statistics(_message.Message):
        """
        TODO: REPLACE
        """

        DESCRIPTOR: _descriptor.Descriptor

        MESSAGES_TOTAL_FIELD_NUMBER: _builtins.int
        MESSAGES_SAVED_FIELD_NUMBER: _builtins.int
        MESSAGES_MAX_FIELD_NUMBER: _builtins.int
        UP_TIME_FIELD_NUMBER: _builtins.int
        REQUESTS_FIELD_NUMBER: _builtins.int
        REQUESTS_HISTORY_FIELD_NUMBER: _builtins.int
        HEARTBEAT_FIELD_NUMBER: _builtins.int
        RETURN_MAX_FIELD_NUMBER: _builtins.int
        RETURN_WINDOW_FIELD_NUMBER: _builtins.int
        messages_total: _builtins.int
        """
        Number of messages we have ever seen
        """
        messages_saved: _builtins.int
        """
        Number of messages we have currently saved our history.
        """
        messages_max: _builtins.int
        """
        Maximum number of messages we will save
        """
        up_time: _builtins.int
        """
        Router uptime in seconds
        """
        requests: _builtins.int
        """
        Number of times any client sent a request to the S&F.
        """
        requests_history: _builtins.int
        """
        Number of times the history was requested.
        """
        heartbeat: _builtins.bool
        """
        Is the heartbeat enabled on the server?
        """
        return_max: _builtins.int
        """
        Maximum number of messages the server will return.
        """
        return_window: _builtins.int
        """
        Maximum history window in minutes the server will return messages from.
        """
        def __init__(
            self,
            *,
            messages_total: _builtins.int = ...,
            messages_saved: _builtins.int = ...,
            messages_max: _builtins.int = ...,
            up_time: _builtins.int = ...,
            requests: _builtins.int = ...,
            requests_history: _builtins.int = ...,
            heartbeat: _builtins.bool = ...,
            return_max: _builtins.int = ...,
            return_window: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["heartbeat", b"heartbeat", "messages_max", b"messages_max", "messages_saved", b"messages_saved", "messages_total", b"messages_total", "requests", b"requests", "requests_history", b"requests_history", "return_max", b"return_max", "return_window", b"return_window", "up_time", b"up_time"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class History(_message.Message):
        """
        TODO: REPLACE
        """

        DESCRIPTOR: _descriptor.Descriptor

        HISTORY_MESSAGES_FIELD_NUMBER: _builtins.int
        WINDOW_FIELD_NUMBER: _builtins.int
        LAST_REQUEST_FIELD_NUMBER: _builtins.int
        history_messages: _builtins.int
        """
        Number of that will be sent to the client
        """
        window: _builtins.int
        """
        The window of messages that was used to filter the history client requested
        """
        last_request: _builtins.int
        """
        Index in the packet history of the last message sent in a previous request to the server.
        Will be sent to the client before sending the history and can be set in a subsequent request to avoid getting packets the server already sent to the client.
        """
        def __init__(
            self,
            *,
            history_messages: _builtins.int = ...,
            window: _builtins.int = ...,
            last_request: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["history_messages", b"history_messages", "last_request", b"last_request", "window", b"window"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Heartbeat(_message.Message):
        """
        TODO: REPLACE
        """

        DESCRIPTOR: _descriptor.Descriptor

        PERIOD_FIELD_NUMBER: _builtins.int
        SECONDARY_FIELD_NUMBER: _builtins.int
        period: _builtins.int
        """
        Period in seconds that the heartbeat is sent out that will be sent to the client
        """
        secondary: _builtins.int
        """
        If set, this is not the primary Store & Forward router on the mesh
        """
        def __init__(
            self,
            *,
            period: _builtins.int = ...,
            secondary: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["period", b"period", "secondary", b"secondary"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    RR_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    HEARTBEAT_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    rr: Global___StoreAndForward.RequestResponse.ValueType
    """
    TODO: REPLACE
    """
    text: _builtins.bytes
    """
    Text from history message.
    """
    @_builtins.property
    def stats(self) -> Global___StoreAndForward.Statistics:
        """
        TODO: REPLACE
        """

    @_builtins.property
    def history(self) -> Global___StoreAndForward.History:
        """
        TODO: REPLACE
        """

    @_builtins.property
    def heartbeat(self) -> Global___StoreAndForward.Heartbeat:
        """
        TODO: REPLACE
        """

    def __init__(
        self,
        *,
        rr: Global___StoreAndForward.RequestResponse.ValueType = ...,
        stats: Global___StoreAndForward.Statistics | None = ...,
        history: Global___StoreAndForward.History | None = ...,
        heartbeat: Global___StoreAndForward.Heartbeat | None = ...,
        text: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["heartbeat", b"heartbeat", "history", b"history", "stats", b"stats", "text", b"text", "variant", b"variant"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["heartbeat", b"heartbeat", "history", b"history", "rr", b"rr", "stats", b"stats", "text", b"text", "variant", b"variant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_variant: _TypeAlias = _typing.Literal["stats", "history", "heartbeat", "text"]  # noqa: Y015
    _WhichOneofArgType_variant: _TypeAlias = _typing.Literal["variant", b"variant"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_variant) -> _WhichOneofReturnType_variant | None: ...

Global___StoreAndForward: _TypeAlias = StoreAndForward  # noqa: Y015
