"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _TelemetrySensorType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TelemetrySensorTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TelemetrySensorType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SENSOR_UNSET: _TelemetrySensorType.ValueType  # 0
    """
    No external telemetry sensor explicitly set
    """
    BME280: _TelemetrySensorType.ValueType  # 1
    """
    High accuracy temperature, pressure, humidity
    """
    BME680: _TelemetrySensorType.ValueType  # 2
    """
    High accuracy temperature, pressure, humidity, and air resistance
    """
    MCP9808: _TelemetrySensorType.ValueType  # 3
    """
    Very high accuracy temperature
    """
    INA260: _TelemetrySensorType.ValueType  # 4
    """
    Moderate accuracy current and voltage
    """
    INA219: _TelemetrySensorType.ValueType  # 5
    """
    Moderate accuracy current and voltage
    """
    BMP280: _TelemetrySensorType.ValueType  # 6
    """
    High accuracy temperature and pressure
    """
    SHTC3: _TelemetrySensorType.ValueType  # 7
    """
    TODO - REMOVE High accuracy temperature and humidity
    """
    LPS22: _TelemetrySensorType.ValueType  # 8
    """
    High accuracy pressure
    """
    QMC6310: _TelemetrySensorType.ValueType  # 9
    """
    3-Axis magnetic sensor
    """
    QMI8658: _TelemetrySensorType.ValueType  # 10
    """
    6-Axis inertial measurement sensor
    """
    QMC5883L: _TelemetrySensorType.ValueType  # 11
    """
    3-Axis magnetic sensor
    """
    SHT31: _TelemetrySensorType.ValueType  # 12
    """
    TODO - REMOVE High accuracy temperature and humidity
    """
    PMSA003I: _TelemetrySensorType.ValueType  # 13
    """
    PM2.5 air quality sensor
    """
    INA3221: _TelemetrySensorType.ValueType  # 14
    """
    INA3221 3 Channel Voltage / Current Sensor
    """
    BMP085: _TelemetrySensorType.ValueType  # 15
    """
    BMP085/BMP180 High accuracy temperature and pressure (older Version of BMP280)
    """
    RCWL9620: _TelemetrySensorType.ValueType  # 16
    """
    RCWL-9620 Doppler Radar Distance Sensor, used for water level detection
    """
    SHT4X: _TelemetrySensorType.ValueType  # 17
    """
    TODO - REMOVE Sensirion High accuracy temperature and humidity
    """
    VEML7700: _TelemetrySensorType.ValueType  # 18
    """
    VEML7700 high accuracy ambient light(Lux) digital 16-bit resolution sensor.
    """
    MLX90632: _TelemetrySensorType.ValueType  # 19
    """
    MLX90632 non-contact IR temperature sensor.
    """
    OPT3001: _TelemetrySensorType.ValueType  # 20
    """
    TI OPT3001 Ambient Light Sensor
    """
    LTR390UV: _TelemetrySensorType.ValueType  # 21
    """
    Lite On LTR-390UV-01 UV Light Sensor
    """
    TSL25911FN: _TelemetrySensorType.ValueType  # 22
    """
    AMS TSL25911FN RGB Light Sensor
    """
    AHT10: _TelemetrySensorType.ValueType  # 23
    """
    AHT10 Integrated temperature and humidity sensor
    """
    DFROBOT_LARK: _TelemetrySensorType.ValueType  # 24
    """
    DFRobot Lark Weather station (temperature, humidity, pressure, wind speed and direction)
    """
    NAU7802: _TelemetrySensorType.ValueType  # 25
    """
    NAU7802 Scale Chip or compatible
    """
    BMP3XX: _TelemetrySensorType.ValueType  # 26
    """
    BMP3XX High accuracy temperature and pressure
    """
    ICM20948: _TelemetrySensorType.ValueType  # 27
    """
    ICM-20948 9-Axis digital motion processor
    """
    MAX17048: _TelemetrySensorType.ValueType  # 28
    """
    MAX17048 1S lipo battery sensor (voltage, state of charge, time to go)
    """
    CUSTOM_SENSOR: _TelemetrySensorType.ValueType  # 29
    """
    Custom I2C sensor implementation based on https://github.com/meshtastic/i2c-sensor
    """
    MAX30102: _TelemetrySensorType.ValueType  # 30
    """
    MAX30102 Pulse Oximeter and Heart-Rate Sensor
    """
    MLX90614: _TelemetrySensorType.ValueType  # 31
    """
    MLX90614 non-contact IR temperature sensor
    """
    SCD4X: _TelemetrySensorType.ValueType  # 32
    """
    SCD40/SCD41 CO2, humidity, temperature sensor
    """
    RADSENS: _TelemetrySensorType.ValueType  # 33
    """
    ClimateGuard RadSens, radiation, Geiger-Muller Tube
    """
    INA226: _TelemetrySensorType.ValueType  # 34
    """
    High accuracy current and voltage
    """
    DFROBOT_RAIN: _TelemetrySensorType.ValueType  # 35
    """
    DFRobot Gravity tipping bucket rain gauge
    """
    DPS310: _TelemetrySensorType.ValueType  # 36
    """
    Infineon DPS310 High accuracy pressure and temperature
    """
    RAK12035: _TelemetrySensorType.ValueType  # 37
    """
    RAKWireless RAK12035 Soil Moisture Sensor Module
    """
    MAX17261: _TelemetrySensorType.ValueType  # 38
    """
    MAX17261 lipo battery gauge
    """
    PCT2075: _TelemetrySensorType.ValueType  # 39
    """
    PCT2075 Temperature Sensor
    """
    ADS1X15: _TelemetrySensorType.ValueType  # 40
    """
    ADS1X15 ADC
    """
    ADS1X15_ALT: _TelemetrySensorType.ValueType  # 41
    """
    ADS1X15 ADC_ALT
    """
    SFA30: _TelemetrySensorType.ValueType  # 42
    """
    Sensirion SFA30 Formaldehyde sensor
    """
    SEN5X: _TelemetrySensorType.ValueType  # 43
    """
    SEN5X PM SENSORS
    """
    TSL2561: _TelemetrySensorType.ValueType  # 44
    """
    TSL2561 light sensor
    """
    BH1750: _TelemetrySensorType.ValueType  # 45
    """
    BH1750 light sensor
    """
    HDC1080: _TelemetrySensorType.ValueType  # 46
    """
    HDC1080 Temperature and Humidity Sensor
    """
    SHT21: _TelemetrySensorType.ValueType  # 47
    """
    TODO - REMOVE STH21 Temperature and R. Humidity sensor
    """
    STC31: _TelemetrySensorType.ValueType  # 48
    """
    Sensirion STC31 CO2 sensor
    """
    SCD30: _TelemetrySensorType.ValueType  # 49
    """
    SCD30 CO2, humidity, temperature sensor
    """
    SHTXX: _TelemetrySensorType.ValueType  # 50
    """
    SHT family of sensors for temperature and humidity
    """
    DS248X: _TelemetrySensorType.ValueType  # 51
    """
    DS248X Bridge for one-wire temperature sensors
    """
    MMC5983MA: _TelemetrySensorType.ValueType  # 52
    """
    MMC5983MA 3-Axis Digital Magnetic Sensor
    """
    ICM42607P: _TelemetrySensorType.ValueType  # 53
    """
    ICM-42607-P 6‑Axis IMU
    """

class TelemetrySensorType(_TelemetrySensorType, metaclass=_TelemetrySensorTypeEnumTypeWrapper):
    """
    Supported I2C Sensors for telemetry in Meshtastic
    """

SENSOR_UNSET: TelemetrySensorType.ValueType  # 0
"""
No external telemetry sensor explicitly set
"""
BME280: TelemetrySensorType.ValueType  # 1
"""
High accuracy temperature, pressure, humidity
"""
BME680: TelemetrySensorType.ValueType  # 2
"""
High accuracy temperature, pressure, humidity, and air resistance
"""
MCP9808: TelemetrySensorType.ValueType  # 3
"""
Very high accuracy temperature
"""
INA260: TelemetrySensorType.ValueType  # 4
"""
Moderate accuracy current and voltage
"""
INA219: TelemetrySensorType.ValueType  # 5
"""
Moderate accuracy current and voltage
"""
BMP280: TelemetrySensorType.ValueType  # 6
"""
High accuracy temperature and pressure
"""
SHTC3: TelemetrySensorType.ValueType  # 7
"""
TODO - REMOVE High accuracy temperature and humidity
"""
LPS22: TelemetrySensorType.ValueType  # 8
"""
High accuracy pressure
"""
QMC6310: TelemetrySensorType.ValueType  # 9
"""
3-Axis magnetic sensor
"""
QMI8658: TelemetrySensorType.ValueType  # 10
"""
6-Axis inertial measurement sensor
"""
QMC5883L: TelemetrySensorType.ValueType  # 11
"""
3-Axis magnetic sensor
"""
SHT31: TelemetrySensorType.ValueType  # 12
"""
TODO - REMOVE High accuracy temperature and humidity
"""
PMSA003I: TelemetrySensorType.ValueType  # 13
"""
PM2.5 air quality sensor
"""
INA3221: TelemetrySensorType.ValueType  # 14
"""
INA3221 3 Channel Voltage / Current Sensor
"""
BMP085: TelemetrySensorType.ValueType  # 15
"""
BMP085/BMP180 High accuracy temperature and pressure (older Version of BMP280)
"""
RCWL9620: TelemetrySensorType.ValueType  # 16
"""
RCWL-9620 Doppler Radar Distance Sensor, used for water level detection
"""
SHT4X: TelemetrySensorType.ValueType  # 17
"""
TODO - REMOVE Sensirion High accuracy temperature and humidity
"""
VEML7700: TelemetrySensorType.ValueType  # 18
"""
VEML7700 high accuracy ambient light(Lux) digital 16-bit resolution sensor.
"""
MLX90632: TelemetrySensorType.ValueType  # 19
"""
MLX90632 non-contact IR temperature sensor.
"""
OPT3001: TelemetrySensorType.ValueType  # 20
"""
TI OPT3001 Ambient Light Sensor
"""
LTR390UV: TelemetrySensorType.ValueType  # 21
"""
Lite On LTR-390UV-01 UV Light Sensor
"""
TSL25911FN: TelemetrySensorType.ValueType  # 22
"""
AMS TSL25911FN RGB Light Sensor
"""
AHT10: TelemetrySensorType.ValueType  # 23
"""
AHT10 Integrated temperature and humidity sensor
"""
DFROBOT_LARK: TelemetrySensorType.ValueType  # 24
"""
DFRobot Lark Weather station (temperature, humidity, pressure, wind speed and direction)
"""
NAU7802: TelemetrySensorType.ValueType  # 25
"""
NAU7802 Scale Chip or compatible
"""
BMP3XX: TelemetrySensorType.ValueType  # 26
"""
BMP3XX High accuracy temperature and pressure
"""
ICM20948: TelemetrySensorType.ValueType  # 27
"""
ICM-20948 9-Axis digital motion processor
"""
MAX17048: TelemetrySensorType.ValueType  # 28
"""
MAX17048 1S lipo battery sensor (voltage, state of charge, time to go)
"""
CUSTOM_SENSOR: TelemetrySensorType.ValueType  # 29
"""
Custom I2C sensor implementation based on https://github.com/meshtastic/i2c-sensor
"""
MAX30102: TelemetrySensorType.ValueType  # 30
"""
MAX30102 Pulse Oximeter and Heart-Rate Sensor
"""
MLX90614: TelemetrySensorType.ValueType  # 31
"""
MLX90614 non-contact IR temperature sensor
"""
SCD4X: TelemetrySensorType.ValueType  # 32
"""
SCD40/SCD41 CO2, humidity, temperature sensor
"""
RADSENS: TelemetrySensorType.ValueType  # 33
"""
ClimateGuard RadSens, radiation, Geiger-Muller Tube
"""
INA226: TelemetrySensorType.ValueType  # 34
"""
High accuracy current and voltage
"""
DFROBOT_RAIN: TelemetrySensorType.ValueType  # 35
"""
DFRobot Gravity tipping bucket rain gauge
"""
DPS310: TelemetrySensorType.ValueType  # 36
"""
Infineon DPS310 High accuracy pressure and temperature
"""
RAK12035: TelemetrySensorType.ValueType  # 37
"""
RAKWireless RAK12035 Soil Moisture Sensor Module
"""
MAX17261: TelemetrySensorType.ValueType  # 38
"""
MAX17261 lipo battery gauge
"""
PCT2075: TelemetrySensorType.ValueType  # 39
"""
PCT2075 Temperature Sensor
"""
ADS1X15: TelemetrySensorType.ValueType  # 40
"""
ADS1X15 ADC
"""
ADS1X15_ALT: TelemetrySensorType.ValueType  # 41
"""
ADS1X15 ADC_ALT
"""
SFA30: TelemetrySensorType.ValueType  # 42
"""
Sensirion SFA30 Formaldehyde sensor
"""
SEN5X: TelemetrySensorType.ValueType  # 43
"""
SEN5X PM SENSORS
"""
TSL2561: TelemetrySensorType.ValueType  # 44
"""
TSL2561 light sensor
"""
BH1750: TelemetrySensorType.ValueType  # 45
"""
BH1750 light sensor
"""
HDC1080: TelemetrySensorType.ValueType  # 46
"""
HDC1080 Temperature and Humidity Sensor
"""
SHT21: TelemetrySensorType.ValueType  # 47
"""
TODO - REMOVE STH21 Temperature and R. Humidity sensor
"""
STC31: TelemetrySensorType.ValueType  # 48
"""
Sensirion STC31 CO2 sensor
"""
SCD30: TelemetrySensorType.ValueType  # 49
"""
SCD30 CO2, humidity, temperature sensor
"""
SHTXX: TelemetrySensorType.ValueType  # 50
"""
SHT family of sensors for temperature and humidity
"""
DS248X: TelemetrySensorType.ValueType  # 51
"""
DS248X Bridge for one-wire temperature sensors
"""
MMC5983MA: TelemetrySensorType.ValueType  # 52
"""
MMC5983MA 3-Axis Digital Magnetic Sensor
"""
ICM42607P: TelemetrySensorType.ValueType  # 53
"""
ICM-42607-P 6‑Axis IMU
"""
Global___TelemetrySensorType: _TypeAlias = TelemetrySensorType  # noqa: Y015

@_typing.final
class DeviceMetrics(_message.Message):
    """
    Key native device metrics such as battery level
    """

    DESCRIPTOR: _descriptor.Descriptor

    BATTERY_LEVEL_FIELD_NUMBER: _builtins.int
    VOLTAGE_FIELD_NUMBER: _builtins.int
    CHANNEL_UTILIZATION_FIELD_NUMBER: _builtins.int
    AIR_UTIL_TX_FIELD_NUMBER: _builtins.int
    UPTIME_SECONDS_FIELD_NUMBER: _builtins.int
    battery_level: _builtins.int
    """
    0-100 (>100 means powered)
    """
    voltage: _builtins.float
    """
    Voltage measured
    """
    channel_utilization: _builtins.float
    """
    Utilization for the current channel, including well formed TX, RX and malformed RX (aka noise).
    """
    air_util_tx: _builtins.float
    """
    Percent of airtime for transmission used within the last hour.
    """
    uptime_seconds: _builtins.int
    """
    How long the device has been running since the last reboot (in seconds)
    """
    def __init__(
        self,
        *,
        battery_level: _builtins.int | None = ...,
        voltage: _builtins.float | None = ...,
        channel_utilization: _builtins.float | None = ...,
        air_util_tx: _builtins.float | None = ...,
        uptime_seconds: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_air_util_tx", b"_air_util_tx", "_battery_level", b"_battery_level", "_channel_utilization", b"_channel_utilization", "_uptime_seconds", b"_uptime_seconds", "_voltage", b"_voltage", "air_util_tx", b"air_util_tx", "battery_level", b"battery_level", "channel_utilization", b"channel_utilization", "uptime_seconds", b"uptime_seconds", "voltage", b"voltage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_air_util_tx", b"_air_util_tx", "_battery_level", b"_battery_level", "_channel_utilization", b"_channel_utilization", "_uptime_seconds", b"_uptime_seconds", "_voltage", b"_voltage", "air_util_tx", b"air_util_tx", "battery_level", b"battery_level", "channel_utilization", b"channel_utilization", "uptime_seconds", b"uptime_seconds", "voltage", b"voltage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__air_util_tx: _TypeAlias = _typing.Literal["air_util_tx"]  # noqa: Y015
    _WhichOneofArgType__air_util_tx: _TypeAlias = _typing.Literal["_air_util_tx", b"_air_util_tx"]  # noqa: Y015
    _WhichOneofReturnType__battery_level: _TypeAlias = _typing.Literal["battery_level"]  # noqa: Y015
    _WhichOneofArgType__battery_level: _TypeAlias = _typing.Literal["_battery_level", b"_battery_level"]  # noqa: Y015
    _WhichOneofReturnType__channel_utilization: _TypeAlias = _typing.Literal["channel_utilization"]  # noqa: Y015
    _WhichOneofArgType__channel_utilization: _TypeAlias = _typing.Literal["_channel_utilization", b"_channel_utilization"]  # noqa: Y015
    _WhichOneofReturnType__uptime_seconds: _TypeAlias = _typing.Literal["uptime_seconds"]  # noqa: Y015
    _WhichOneofArgType__uptime_seconds: _TypeAlias = _typing.Literal["_uptime_seconds", b"_uptime_seconds"]  # noqa: Y015
    _WhichOneofReturnType__voltage: _TypeAlias = _typing.Literal["voltage"]  # noqa: Y015
    _WhichOneofArgType__voltage: _TypeAlias = _typing.Literal["_voltage", b"_voltage"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__air_util_tx) -> _WhichOneofReturnType__air_util_tx | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__battery_level) -> _WhichOneofReturnType__battery_level | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__channel_utilization) -> _WhichOneofReturnType__channel_utilization | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__uptime_seconds) -> _WhichOneofReturnType__uptime_seconds | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voltage) -> _WhichOneofReturnType__voltage | None: ...

Global___DeviceMetrics: _TypeAlias = DeviceMetrics  # noqa: Y015

@_typing.final
class EnvironmentMetrics(_message.Message):
    """
    Weather station or other environmental metrics
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEMPERATURE_FIELD_NUMBER: _builtins.int
    RELATIVE_HUMIDITY_FIELD_NUMBER: _builtins.int
    BAROMETRIC_PRESSURE_FIELD_NUMBER: _builtins.int
    GAS_RESISTANCE_FIELD_NUMBER: _builtins.int
    VOLTAGE_FIELD_NUMBER: _builtins.int
    CURRENT_FIELD_NUMBER: _builtins.int
    IAQ_FIELD_NUMBER: _builtins.int
    DISTANCE_FIELD_NUMBER: _builtins.int
    LUX_FIELD_NUMBER: _builtins.int
    WHITE_LUX_FIELD_NUMBER: _builtins.int
    IR_LUX_FIELD_NUMBER: _builtins.int
    UV_LUX_FIELD_NUMBER: _builtins.int
    WIND_DIRECTION_FIELD_NUMBER: _builtins.int
    WIND_SPEED_FIELD_NUMBER: _builtins.int
    WEIGHT_FIELD_NUMBER: _builtins.int
    WIND_GUST_FIELD_NUMBER: _builtins.int
    WIND_LULL_FIELD_NUMBER: _builtins.int
    RADIATION_FIELD_NUMBER: _builtins.int
    RAINFALL_1H_FIELD_NUMBER: _builtins.int
    RAINFALL_24H_FIELD_NUMBER: _builtins.int
    SOIL_MOISTURE_FIELD_NUMBER: _builtins.int
    SOIL_TEMPERATURE_FIELD_NUMBER: _builtins.int
    ONE_WIRE_TEMPERATURE_FIELD_NUMBER: _builtins.int
    temperature: _builtins.float
    """
    Temperature measured
    """
    relative_humidity: _builtins.float
    """
    Relative humidity percent measured
    """
    barometric_pressure: _builtins.float
    """
    Barometric pressure in hPA measured
    """
    gas_resistance: _builtins.float
    """
    Gas resistance in MOhm measured
    """
    voltage: _builtins.float
    """
    Voltage measured (To be depreciated in favor of PowerMetrics in Meshtastic 3.x)
    """
    current: _builtins.float
    """
    Current measured (To be depreciated in favor of PowerMetrics in Meshtastic 3.x)
    """
    iaq: _builtins.int
    """
    relative scale IAQ value as measured by Bosch BME680 . value 0-500.
    Belongs to Air Quality but is not particle but VOC measurement. Other VOC values can also be put in here.
    """
    distance: _builtins.float
    """
    RCWL9620 Doppler Radar Distance Sensor, used for water level detection. Float value in mm.
    """
    lux: _builtins.float
    """
    VEML7700 high accuracy ambient light(Lux) digital 16-bit resolution sensor.
    """
    white_lux: _builtins.float
    """
    VEML7700 high accuracy white light(irradiance) not calibrated digital 16-bit resolution sensor.
    """
    ir_lux: _builtins.float
    """
    Infrared lux
    """
    uv_lux: _builtins.float
    """
    Ultraviolet lux
    """
    wind_direction: _builtins.int
    """
    Wind direction in degrees
    0 degrees = North, 90 = East, etc...
    """
    wind_speed: _builtins.float
    """
    Wind speed in m/s
    """
    weight: _builtins.float
    """
    Weight in KG
    """
    wind_gust: _builtins.float
    """
    Wind gust in m/s
    """
    wind_lull: _builtins.float
    """
    Wind lull in m/s
    """
    radiation: _builtins.float
    """
    Radiation in µR/h
    """
    rainfall_1h: _builtins.float
    """
    Rainfall in the last hour in mm
    """
    rainfall_24h: _builtins.float
    """
    Rainfall in the last 24 hours in mm
    """
    soil_moisture: _builtins.int
    """
    Soil moisture measured (% 1-100)
    """
    soil_temperature: _builtins.float
    """
    Soil temperature measured (*C)
    """
    @_builtins.property
    def one_wire_temperature(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """
        One-wire temperature (*C)
        """

    def __init__(
        self,
        *,
        temperature: _builtins.float | None = ...,
        relative_humidity: _builtins.float | None = ...,
        barometric_pressure: _builtins.float | None = ...,
        gas_resistance: _builtins.float | None = ...,
        voltage: _builtins.float | None = ...,
        current: _builtins.float | None = ...,
        iaq: _builtins.int | None = ...,
        distance: _builtins.float | None = ...,
        lux: _builtins.float | None = ...,
        white_lux: _builtins.float | None = ...,
        ir_lux: _builtins.float | None = ...,
        uv_lux: _builtins.float | None = ...,
        wind_direction: _builtins.int | None = ...,
        wind_speed: _builtins.float | None = ...,
        weight: _builtins.float | None = ...,
        wind_gust: _builtins.float | None = ...,
        wind_lull: _builtins.float | None = ...,
        radiation: _builtins.float | None = ...,
        rainfall_1h: _builtins.float | None = ...,
        rainfall_24h: _builtins.float | None = ...,
        soil_moisture: _builtins.int | None = ...,
        soil_temperature: _builtins.float | None = ...,
        one_wire_temperature: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_barometric_pressure", b"_barometric_pressure", "_current", b"_current", "_distance", b"_distance", "_gas_resistance", b"_gas_resistance", "_iaq", b"_iaq", "_ir_lux", b"_ir_lux", "_lux", b"_lux", "_radiation", b"_radiation", "_rainfall_1h", b"_rainfall_1h", "_rainfall_24h", b"_rainfall_24h", "_relative_humidity", b"_relative_humidity", "_soil_moisture", b"_soil_moisture", "_soil_temperature", b"_soil_temperature", "_temperature", b"_temperature", "_uv_lux", b"_uv_lux", "_voltage", b"_voltage", "_weight", b"_weight", "_white_lux", b"_white_lux", "_wind_direction", b"_wind_direction", "_wind_gust", b"_wind_gust", "_wind_lull", b"_wind_lull", "_wind_speed", b"_wind_speed", "barometric_pressure", b"barometric_pressure", "current", b"current", "distance", b"distance", "gas_resistance", b"gas_resistance", "iaq", b"iaq", "ir_lux", b"ir_lux", "lux", b"lux", "radiation", b"radiation", "rainfall_1h", b"rainfall_1h", "rainfall_24h", b"rainfall_24h", "relative_humidity", b"relative_humidity", "soil_moisture", b"soil_moisture", "soil_temperature", b"soil_temperature", "temperature", b"temperature", "uv_lux", b"uv_lux", "voltage", b"voltage", "weight", b"weight", "white_lux", b"white_lux", "wind_direction", b"wind_direction", "wind_gust", b"wind_gust", "wind_lull", b"wind_lull", "wind_speed", b"wind_speed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_barometric_pressure", b"_barometric_pressure", "_current", b"_current", "_distance", b"_distance", "_gas_resistance", b"_gas_resistance", "_iaq", b"_iaq", "_ir_lux", b"_ir_lux", "_lux", b"_lux", "_radiation", b"_radiation", "_rainfall_1h", b"_rainfall_1h", "_rainfall_24h", b"_rainfall_24h", "_relative_humidity", b"_relative_humidity", "_soil_moisture", b"_soil_moisture", "_soil_temperature", b"_soil_temperature", "_temperature", b"_temperature", "_uv_lux", b"_uv_lux", "_voltage", b"_voltage", "_weight", b"_weight", "_white_lux", b"_white_lux", "_wind_direction", b"_wind_direction", "_wind_gust", b"_wind_gust", "_wind_lull", b"_wind_lull", "_wind_speed", b"_wind_speed", "barometric_pressure", b"barometric_pressure", "current", b"current", "distance", b"distance", "gas_resistance", b"gas_resistance", "iaq", b"iaq", "ir_lux", b"ir_lux", "lux", b"lux", "one_wire_temperature", b"one_wire_temperature", "radiation", b"radiation", "rainfall_1h", b"rainfall_1h", "rainfall_24h", b"rainfall_24h", "relative_humidity", b"relative_humidity", "soil_moisture", b"soil_moisture", "soil_temperature", b"soil_temperature", "temperature", b"temperature", "uv_lux", b"uv_lux", "voltage", b"voltage", "weight", b"weight", "white_lux", b"white_lux", "wind_direction", b"wind_direction", "wind_gust", b"wind_gust", "wind_lull", b"wind_lull", "wind_speed", b"wind_speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__barometric_pressure: _TypeAlias = _typing.Literal["barometric_pressure"]  # noqa: Y015
    _WhichOneofArgType__barometric_pressure: _TypeAlias = _typing.Literal["_barometric_pressure", b"_barometric_pressure"]  # noqa: Y015
    _WhichOneofReturnType__current: _TypeAlias = _typing.Literal["current"]  # noqa: Y015
    _WhichOneofArgType__current: _TypeAlias = _typing.Literal["_current", b"_current"]  # noqa: Y015
    _WhichOneofReturnType__distance: _TypeAlias = _typing.Literal["distance"]  # noqa: Y015
    _WhichOneofArgType__distance: _TypeAlias = _typing.Literal["_distance", b"_distance"]  # noqa: Y015
    _WhichOneofReturnType__gas_resistance: _TypeAlias = _typing.Literal["gas_resistance"]  # noqa: Y015
    _WhichOneofArgType__gas_resistance: _TypeAlias = _typing.Literal["_gas_resistance", b"_gas_resistance"]  # noqa: Y015
    _WhichOneofReturnType__iaq: _TypeAlias = _typing.Literal["iaq"]  # noqa: Y015
    _WhichOneofArgType__iaq: _TypeAlias = _typing.Literal["_iaq", b"_iaq"]  # noqa: Y015
    _WhichOneofReturnType__ir_lux: _TypeAlias = _typing.Literal["ir_lux"]  # noqa: Y015
    _WhichOneofArgType__ir_lux: _TypeAlias = _typing.Literal["_ir_lux", b"_ir_lux"]  # noqa: Y015
    _WhichOneofReturnType__lux: _TypeAlias = _typing.Literal["lux"]  # noqa: Y015
    _WhichOneofArgType__lux: _TypeAlias = _typing.Literal["_lux", b"_lux"]  # noqa: Y015
    _WhichOneofReturnType__radiation: _TypeAlias = _typing.Literal["radiation"]  # noqa: Y015
    _WhichOneofArgType__radiation: _TypeAlias = _typing.Literal["_radiation", b"_radiation"]  # noqa: Y015
    _WhichOneofReturnType__rainfall_1h: _TypeAlias = _typing.Literal["rainfall_1h"]  # noqa: Y015
    _WhichOneofArgType__rainfall_1h: _TypeAlias = _typing.Literal["_rainfall_1h", b"_rainfall_1h"]  # noqa: Y015
    _WhichOneofReturnType__rainfall_24h: _TypeAlias = _typing.Literal["rainfall_24h"]  # noqa: Y015
    _WhichOneofArgType__rainfall_24h: _TypeAlias = _typing.Literal["_rainfall_24h", b"_rainfall_24h"]  # noqa: Y015
    _WhichOneofReturnType__relative_humidity: _TypeAlias = _typing.Literal["relative_humidity"]  # noqa: Y015
    _WhichOneofArgType__relative_humidity: _TypeAlias = _typing.Literal["_relative_humidity", b"_relative_humidity"]  # noqa: Y015
    _WhichOneofReturnType__soil_moisture: _TypeAlias = _typing.Literal["soil_moisture"]  # noqa: Y015
    _WhichOneofArgType__soil_moisture: _TypeAlias = _typing.Literal["_soil_moisture", b"_soil_moisture"]  # noqa: Y015
    _WhichOneofReturnType__soil_temperature: _TypeAlias = _typing.Literal["soil_temperature"]  # noqa: Y015
    _WhichOneofArgType__soil_temperature: _TypeAlias = _typing.Literal["_soil_temperature", b"_soil_temperature"]  # noqa: Y015
    _WhichOneofReturnType__temperature: _TypeAlias = _typing.Literal["temperature"]  # noqa: Y015
    _WhichOneofArgType__temperature: _TypeAlias = _typing.Literal["_temperature", b"_temperature"]  # noqa: Y015
    _WhichOneofReturnType__uv_lux: _TypeAlias = _typing.Literal["uv_lux"]  # noqa: Y015
    _WhichOneofArgType__uv_lux: _TypeAlias = _typing.Literal["_uv_lux", b"_uv_lux"]  # noqa: Y015
    _WhichOneofReturnType__voltage: _TypeAlias = _typing.Literal["voltage"]  # noqa: Y015
    _WhichOneofArgType__voltage: _TypeAlias = _typing.Literal["_voltage", b"_voltage"]  # noqa: Y015
    _WhichOneofReturnType__weight: _TypeAlias = _typing.Literal["weight"]  # noqa: Y015
    _WhichOneofArgType__weight: _TypeAlias = _typing.Literal["_weight", b"_weight"]  # noqa: Y015
    _WhichOneofReturnType__white_lux: _TypeAlias = _typing.Literal["white_lux"]  # noqa: Y015
    _WhichOneofArgType__white_lux: _TypeAlias = _typing.Literal["_white_lux", b"_white_lux"]  # noqa: Y015
    _WhichOneofReturnType__wind_direction: _TypeAlias = _typing.Literal["wind_direction"]  # noqa: Y015
    _WhichOneofArgType__wind_direction: _TypeAlias = _typing.Literal["_wind_direction", b"_wind_direction"]  # noqa: Y015
    _WhichOneofReturnType__wind_gust: _TypeAlias = _typing.Literal["wind_gust"]  # noqa: Y015
    _WhichOneofArgType__wind_gust: _TypeAlias = _typing.Literal["_wind_gust", b"_wind_gust"]  # noqa: Y015
    _WhichOneofReturnType__wind_lull: _TypeAlias = _typing.Literal["wind_lull"]  # noqa: Y015
    _WhichOneofArgType__wind_lull: _TypeAlias = _typing.Literal["_wind_lull", b"_wind_lull"]  # noqa: Y015
    _WhichOneofReturnType__wind_speed: _TypeAlias = _typing.Literal["wind_speed"]  # noqa: Y015
    _WhichOneofArgType__wind_speed: _TypeAlias = _typing.Literal["_wind_speed", b"_wind_speed"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__barometric_pressure) -> _WhichOneofReturnType__barometric_pressure | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__current) -> _WhichOneofReturnType__current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__distance) -> _WhichOneofReturnType__distance | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gas_resistance) -> _WhichOneofReturnType__gas_resistance | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__iaq) -> _WhichOneofReturnType__iaq | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ir_lux) -> _WhichOneofReturnType__ir_lux | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__lux) -> _WhichOneofReturnType__lux | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__radiation) -> _WhichOneofReturnType__radiation | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rainfall_1h) -> _WhichOneofReturnType__rainfall_1h | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rainfall_24h) -> _WhichOneofReturnType__rainfall_24h | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__relative_humidity) -> _WhichOneofReturnType__relative_humidity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__soil_moisture) -> _WhichOneofReturnType__soil_moisture | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__soil_temperature) -> _WhichOneofReturnType__soil_temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__temperature) -> _WhichOneofReturnType__temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__uv_lux) -> _WhichOneofReturnType__uv_lux | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voltage) -> _WhichOneofReturnType__voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__weight) -> _WhichOneofReturnType__weight | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__white_lux) -> _WhichOneofReturnType__white_lux | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__wind_direction) -> _WhichOneofReturnType__wind_direction | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__wind_gust) -> _WhichOneofReturnType__wind_gust | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__wind_lull) -> _WhichOneofReturnType__wind_lull | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__wind_speed) -> _WhichOneofReturnType__wind_speed | None: ...

Global___EnvironmentMetrics: _TypeAlias = EnvironmentMetrics  # noqa: Y015

@_typing.final
class PowerMetrics(_message.Message):
    """
    Power Metrics (voltage / current / etc)
    """

    DESCRIPTOR: _descriptor.Descriptor

    CH1_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH1_CURRENT_FIELD_NUMBER: _builtins.int
    CH2_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH2_CURRENT_FIELD_NUMBER: _builtins.int
    CH3_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH3_CURRENT_FIELD_NUMBER: _builtins.int
    CH4_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH4_CURRENT_FIELD_NUMBER: _builtins.int
    CH5_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH5_CURRENT_FIELD_NUMBER: _builtins.int
    CH6_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH6_CURRENT_FIELD_NUMBER: _builtins.int
    CH7_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH7_CURRENT_FIELD_NUMBER: _builtins.int
    CH8_VOLTAGE_FIELD_NUMBER: _builtins.int
    CH8_CURRENT_FIELD_NUMBER: _builtins.int
    ch1_voltage: _builtins.float
    """
    Voltage (Ch1)
    """
    ch1_current: _builtins.float
    """
    Current (Ch1)
    """
    ch2_voltage: _builtins.float
    """
    Voltage (Ch2)
    """
    ch2_current: _builtins.float
    """
    Current (Ch2)
    """
    ch3_voltage: _builtins.float
    """
    Voltage (Ch3)
    """
    ch3_current: _builtins.float
    """
    Current (Ch3)
    """
    ch4_voltage: _builtins.float
    """
    Voltage (Ch4)
    """
    ch4_current: _builtins.float
    """
    Current (Ch4)
    """
    ch5_voltage: _builtins.float
    """
    Voltage (Ch5)
    """
    ch5_current: _builtins.float
    """
    Current (Ch5)
    """
    ch6_voltage: _builtins.float
    """
    Voltage (Ch6)
    """
    ch6_current: _builtins.float
    """
    Current (Ch6)
    """
    ch7_voltage: _builtins.float
    """
    Voltage (Ch7)
    """
    ch7_current: _builtins.float
    """
    Current (Ch7)
    """
    ch8_voltage: _builtins.float
    """
    Voltage (Ch8)
    """
    ch8_current: _builtins.float
    """
    Current (Ch8)
    """
    def __init__(
        self,
        *,
        ch1_voltage: _builtins.float | None = ...,
        ch1_current: _builtins.float | None = ...,
        ch2_voltage: _builtins.float | None = ...,
        ch2_current: _builtins.float | None = ...,
        ch3_voltage: _builtins.float | None = ...,
        ch3_current: _builtins.float | None = ...,
        ch4_voltage: _builtins.float | None = ...,
        ch4_current: _builtins.float | None = ...,
        ch5_voltage: _builtins.float | None = ...,
        ch5_current: _builtins.float | None = ...,
        ch6_voltage: _builtins.float | None = ...,
        ch6_current: _builtins.float | None = ...,
        ch7_voltage: _builtins.float | None = ...,
        ch7_current: _builtins.float | None = ...,
        ch8_voltage: _builtins.float | None = ...,
        ch8_current: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_ch1_current", b"_ch1_current", "_ch1_voltage", b"_ch1_voltage", "_ch2_current", b"_ch2_current", "_ch2_voltage", b"_ch2_voltage", "_ch3_current", b"_ch3_current", "_ch3_voltage", b"_ch3_voltage", "_ch4_current", b"_ch4_current", "_ch4_voltage", b"_ch4_voltage", "_ch5_current", b"_ch5_current", "_ch5_voltage", b"_ch5_voltage", "_ch6_current", b"_ch6_current", "_ch6_voltage", b"_ch6_voltage", "_ch7_current", b"_ch7_current", "_ch7_voltage", b"_ch7_voltage", "_ch8_current", b"_ch8_current", "_ch8_voltage", b"_ch8_voltage", "ch1_current", b"ch1_current", "ch1_voltage", b"ch1_voltage", "ch2_current", b"ch2_current", "ch2_voltage", b"ch2_voltage", "ch3_current", b"ch3_current", "ch3_voltage", b"ch3_voltage", "ch4_current", b"ch4_current", "ch4_voltage", b"ch4_voltage", "ch5_current", b"ch5_current", "ch5_voltage", b"ch5_voltage", "ch6_current", b"ch6_current", "ch6_voltage", b"ch6_voltage", "ch7_current", b"ch7_current", "ch7_voltage", b"ch7_voltage", "ch8_current", b"ch8_current", "ch8_voltage", b"ch8_voltage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_ch1_current", b"_ch1_current", "_ch1_voltage", b"_ch1_voltage", "_ch2_current", b"_ch2_current", "_ch2_voltage", b"_ch2_voltage", "_ch3_current", b"_ch3_current", "_ch3_voltage", b"_ch3_voltage", "_ch4_current", b"_ch4_current", "_ch4_voltage", b"_ch4_voltage", "_ch5_current", b"_ch5_current", "_ch5_voltage", b"_ch5_voltage", "_ch6_current", b"_ch6_current", "_ch6_voltage", b"_ch6_voltage", "_ch7_current", b"_ch7_current", "_ch7_voltage", b"_ch7_voltage", "_ch8_current", b"_ch8_current", "_ch8_voltage", b"_ch8_voltage", "ch1_current", b"ch1_current", "ch1_voltage", b"ch1_voltage", "ch2_current", b"ch2_current", "ch2_voltage", b"ch2_voltage", "ch3_current", b"ch3_current", "ch3_voltage", b"ch3_voltage", "ch4_current", b"ch4_current", "ch4_voltage", b"ch4_voltage", "ch5_current", b"ch5_current", "ch5_voltage", b"ch5_voltage", "ch6_current", b"ch6_current", "ch6_voltage", b"ch6_voltage", "ch7_current", b"ch7_current", "ch7_voltage", b"ch7_voltage", "ch8_current", b"ch8_current", "ch8_voltage", b"ch8_voltage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__ch1_current: _TypeAlias = _typing.Literal["ch1_current"]  # noqa: Y015
    _WhichOneofArgType__ch1_current: _TypeAlias = _typing.Literal["_ch1_current", b"_ch1_current"]  # noqa: Y015
    _WhichOneofReturnType__ch1_voltage: _TypeAlias = _typing.Literal["ch1_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch1_voltage: _TypeAlias = _typing.Literal["_ch1_voltage", b"_ch1_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch2_current: _TypeAlias = _typing.Literal["ch2_current"]  # noqa: Y015
    _WhichOneofArgType__ch2_current: _TypeAlias = _typing.Literal["_ch2_current", b"_ch2_current"]  # noqa: Y015
    _WhichOneofReturnType__ch2_voltage: _TypeAlias = _typing.Literal["ch2_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch2_voltage: _TypeAlias = _typing.Literal["_ch2_voltage", b"_ch2_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch3_current: _TypeAlias = _typing.Literal["ch3_current"]  # noqa: Y015
    _WhichOneofArgType__ch3_current: _TypeAlias = _typing.Literal["_ch3_current", b"_ch3_current"]  # noqa: Y015
    _WhichOneofReturnType__ch3_voltage: _TypeAlias = _typing.Literal["ch3_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch3_voltage: _TypeAlias = _typing.Literal["_ch3_voltage", b"_ch3_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch4_current: _TypeAlias = _typing.Literal["ch4_current"]  # noqa: Y015
    _WhichOneofArgType__ch4_current: _TypeAlias = _typing.Literal["_ch4_current", b"_ch4_current"]  # noqa: Y015
    _WhichOneofReturnType__ch4_voltage: _TypeAlias = _typing.Literal["ch4_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch4_voltage: _TypeAlias = _typing.Literal["_ch4_voltage", b"_ch4_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch5_current: _TypeAlias = _typing.Literal["ch5_current"]  # noqa: Y015
    _WhichOneofArgType__ch5_current: _TypeAlias = _typing.Literal["_ch5_current", b"_ch5_current"]  # noqa: Y015
    _WhichOneofReturnType__ch5_voltage: _TypeAlias = _typing.Literal["ch5_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch5_voltage: _TypeAlias = _typing.Literal["_ch5_voltage", b"_ch5_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch6_current: _TypeAlias = _typing.Literal["ch6_current"]  # noqa: Y015
    _WhichOneofArgType__ch6_current: _TypeAlias = _typing.Literal["_ch6_current", b"_ch6_current"]  # noqa: Y015
    _WhichOneofReturnType__ch6_voltage: _TypeAlias = _typing.Literal["ch6_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch6_voltage: _TypeAlias = _typing.Literal["_ch6_voltage", b"_ch6_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch7_current: _TypeAlias = _typing.Literal["ch7_current"]  # noqa: Y015
    _WhichOneofArgType__ch7_current: _TypeAlias = _typing.Literal["_ch7_current", b"_ch7_current"]  # noqa: Y015
    _WhichOneofReturnType__ch7_voltage: _TypeAlias = _typing.Literal["ch7_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch7_voltage: _TypeAlias = _typing.Literal["_ch7_voltage", b"_ch7_voltage"]  # noqa: Y015
    _WhichOneofReturnType__ch8_current: _TypeAlias = _typing.Literal["ch8_current"]  # noqa: Y015
    _WhichOneofArgType__ch8_current: _TypeAlias = _typing.Literal["_ch8_current", b"_ch8_current"]  # noqa: Y015
    _WhichOneofReturnType__ch8_voltage: _TypeAlias = _typing.Literal["ch8_voltage"]  # noqa: Y015
    _WhichOneofArgType__ch8_voltage: _TypeAlias = _typing.Literal["_ch8_voltage", b"_ch8_voltage"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch1_current) -> _WhichOneofReturnType__ch1_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch1_voltage) -> _WhichOneofReturnType__ch1_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch2_current) -> _WhichOneofReturnType__ch2_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch2_voltage) -> _WhichOneofReturnType__ch2_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch3_current) -> _WhichOneofReturnType__ch3_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch3_voltage) -> _WhichOneofReturnType__ch3_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch4_current) -> _WhichOneofReturnType__ch4_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch4_voltage) -> _WhichOneofReturnType__ch4_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch5_current) -> _WhichOneofReturnType__ch5_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch5_voltage) -> _WhichOneofReturnType__ch5_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch6_current) -> _WhichOneofReturnType__ch6_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch6_voltage) -> _WhichOneofReturnType__ch6_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch7_current) -> _WhichOneofReturnType__ch7_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch7_voltage) -> _WhichOneofReturnType__ch7_voltage | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch8_current) -> _WhichOneofReturnType__ch8_current | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ch8_voltage) -> _WhichOneofReturnType__ch8_voltage | None: ...

Global___PowerMetrics: _TypeAlias = PowerMetrics  # noqa: Y015

@_typing.final
class AirQualityMetrics(_message.Message):
    """
    Air quality metrics
    """

    DESCRIPTOR: _descriptor.Descriptor

    PM10_STANDARD_FIELD_NUMBER: _builtins.int
    PM25_STANDARD_FIELD_NUMBER: _builtins.int
    PM100_STANDARD_FIELD_NUMBER: _builtins.int
    PM10_ENVIRONMENTAL_FIELD_NUMBER: _builtins.int
    PM25_ENVIRONMENTAL_FIELD_NUMBER: _builtins.int
    PM100_ENVIRONMENTAL_FIELD_NUMBER: _builtins.int
    PARTICLES_03UM_FIELD_NUMBER: _builtins.int
    PARTICLES_05UM_FIELD_NUMBER: _builtins.int
    PARTICLES_10UM_FIELD_NUMBER: _builtins.int
    PARTICLES_25UM_FIELD_NUMBER: _builtins.int
    PARTICLES_50UM_FIELD_NUMBER: _builtins.int
    PARTICLES_100UM_FIELD_NUMBER: _builtins.int
    CO2_FIELD_NUMBER: _builtins.int
    CO2_TEMPERATURE_FIELD_NUMBER: _builtins.int
    CO2_HUMIDITY_FIELD_NUMBER: _builtins.int
    FORM_FORMALDEHYDE_FIELD_NUMBER: _builtins.int
    FORM_HUMIDITY_FIELD_NUMBER: _builtins.int
    FORM_TEMPERATURE_FIELD_NUMBER: _builtins.int
    PM40_STANDARD_FIELD_NUMBER: _builtins.int
    PARTICLES_40UM_FIELD_NUMBER: _builtins.int
    PM_TEMPERATURE_FIELD_NUMBER: _builtins.int
    PM_HUMIDITY_FIELD_NUMBER: _builtins.int
    PM_VOC_IDX_FIELD_NUMBER: _builtins.int
    PM_NOX_IDX_FIELD_NUMBER: _builtins.int
    PARTICLES_TPS_FIELD_NUMBER: _builtins.int
    pm10_standard: _builtins.int
    """
    Concentration Units Standard PM1.0 in ug/m3
    """
    pm25_standard: _builtins.int
    """
    Concentration Units Standard PM2.5 in ug/m3
    """
    pm100_standard: _builtins.int
    """
    Concentration Units Standard PM10.0 in ug/m3
    """
    pm10_environmental: _builtins.int
    """
    Concentration Units Environmental PM1.0 in ug/m3
    """
    pm25_environmental: _builtins.int
    """
    Concentration Units Environmental PM2.5 in ug/m3
    """
    pm100_environmental: _builtins.int
    """
    Concentration Units Environmental PM10.0 in ug/m3
    """
    particles_03um: _builtins.int
    """
    0.3um Particle Count in #/0.1l
    """
    particles_05um: _builtins.int
    """
    0.5um Particle Count in #/0.1l
    """
    particles_10um: _builtins.int
    """
    1.0um Particle Count in #/0.1l
    """
    particles_25um: _builtins.int
    """
    2.5um Particle Count in #/0.1l
    """
    particles_50um: _builtins.int
    """
    5.0um Particle Count in #/0.1l
    """
    particles_100um: _builtins.int
    """
    10.0um Particle Count in #/0.1l
    """
    co2: _builtins.int
    """
    CO2 concentration in ppm
    """
    co2_temperature: _builtins.float
    """
    CO2 sensor temperature in degC
    """
    co2_humidity: _builtins.float
    """
    CO2 sensor relative humidity in %
    """
    form_formaldehyde: _builtins.float
    """
    Formaldehyde sensor formaldehyde concentration in ppb
    """
    form_humidity: _builtins.float
    """
    Formaldehyde sensor relative humidity in %RH
    """
    form_temperature: _builtins.float
    """
    Formaldehyde sensor temperature in degrees Celsius
    """
    pm40_standard: _builtins.int
    """
    Concentration Units Standard PM4.0 in ug/m3
    """
    particles_40um: _builtins.int
    """
    4.0um Particle Count in #/0.1l
    """
    pm_temperature: _builtins.float
    """
    PM Sensor Temperature
    """
    pm_humidity: _builtins.float
    """
    PM Sensor humidity
    """
    pm_voc_idx: _builtins.float
    """
    PM Sensor VOC Index
    """
    pm_nox_idx: _builtins.float
    """
    PM Sensor NOx Index
    """
    particles_tps: _builtins.float
    """
    Typical Particle Size in um
    """
    def __init__(
        self,
        *,
        pm10_standard: _builtins.int | None = ...,
        pm25_standard: _builtins.int | None = ...,
        pm100_standard: _builtins.int | None = ...,
        pm10_environmental: _builtins.int | None = ...,
        pm25_environmental: _builtins.int | None = ...,
        pm100_environmental: _builtins.int | None = ...,
        particles_03um: _builtins.int | None = ...,
        particles_05um: _builtins.int | None = ...,
        particles_10um: _builtins.int | None = ...,
        particles_25um: _builtins.int | None = ...,
        particles_50um: _builtins.int | None = ...,
        particles_100um: _builtins.int | None = ...,
        co2: _builtins.int | None = ...,
        co2_temperature: _builtins.float | None = ...,
        co2_humidity: _builtins.float | None = ...,
        form_formaldehyde: _builtins.float | None = ...,
        form_humidity: _builtins.float | None = ...,
        form_temperature: _builtins.float | None = ...,
        pm40_standard: _builtins.int | None = ...,
        particles_40um: _builtins.int | None = ...,
        pm_temperature: _builtins.float | None = ...,
        pm_humidity: _builtins.float | None = ...,
        pm_voc_idx: _builtins.float | None = ...,
        pm_nox_idx: _builtins.float | None = ...,
        particles_tps: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_co2", b"_co2", "_co2_humidity", b"_co2_humidity", "_co2_temperature", b"_co2_temperature", "_form_formaldehyde", b"_form_formaldehyde", "_form_humidity", b"_form_humidity", "_form_temperature", b"_form_temperature", "_particles_03um", b"_particles_03um", "_particles_05um", b"_particles_05um", "_particles_100um", b"_particles_100um", "_particles_10um", b"_particles_10um", "_particles_25um", b"_particles_25um", "_particles_40um", b"_particles_40um", "_particles_50um", b"_particles_50um", "_particles_tps", b"_particles_tps", "_pm100_environmental", b"_pm100_environmental", "_pm100_standard", b"_pm100_standard", "_pm10_environmental", b"_pm10_environmental", "_pm10_standard", b"_pm10_standard", "_pm25_environmental", b"_pm25_environmental", "_pm25_standard", b"_pm25_standard", "_pm40_standard", b"_pm40_standard", "_pm_humidity", b"_pm_humidity", "_pm_nox_idx", b"_pm_nox_idx", "_pm_temperature", b"_pm_temperature", "_pm_voc_idx", b"_pm_voc_idx", "co2", b"co2", "co2_humidity", b"co2_humidity", "co2_temperature", b"co2_temperature", "form_formaldehyde", b"form_formaldehyde", "form_humidity", b"form_humidity", "form_temperature", b"form_temperature", "particles_03um", b"particles_03um", "particles_05um", b"particles_05um", "particles_100um", b"particles_100um", "particles_10um", b"particles_10um", "particles_25um", b"particles_25um", "particles_40um", b"particles_40um", "particles_50um", b"particles_50um", "particles_tps", b"particles_tps", "pm100_environmental", b"pm100_environmental", "pm100_standard", b"pm100_standard", "pm10_environmental", b"pm10_environmental", "pm10_standard", b"pm10_standard", "pm25_environmental", b"pm25_environmental", "pm25_standard", b"pm25_standard", "pm40_standard", b"pm40_standard", "pm_humidity", b"pm_humidity", "pm_nox_idx", b"pm_nox_idx", "pm_temperature", b"pm_temperature", "pm_voc_idx", b"pm_voc_idx"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_co2", b"_co2", "_co2_humidity", b"_co2_humidity", "_co2_temperature", b"_co2_temperature", "_form_formaldehyde", b"_form_formaldehyde", "_form_humidity", b"_form_humidity", "_form_temperature", b"_form_temperature", "_particles_03um", b"_particles_03um", "_particles_05um", b"_particles_05um", "_particles_100um", b"_particles_100um", "_particles_10um", b"_particles_10um", "_particles_25um", b"_particles_25um", "_particles_40um", b"_particles_40um", "_particles_50um", b"_particles_50um", "_particles_tps", b"_particles_tps", "_pm100_environmental", b"_pm100_environmental", "_pm100_standard", b"_pm100_standard", "_pm10_environmental", b"_pm10_environmental", "_pm10_standard", b"_pm10_standard", "_pm25_environmental", b"_pm25_environmental", "_pm25_standard", b"_pm25_standard", "_pm40_standard", b"_pm40_standard", "_pm_humidity", b"_pm_humidity", "_pm_nox_idx", b"_pm_nox_idx", "_pm_temperature", b"_pm_temperature", "_pm_voc_idx", b"_pm_voc_idx", "co2", b"co2", "co2_humidity", b"co2_humidity", "co2_temperature", b"co2_temperature", "form_formaldehyde", b"form_formaldehyde", "form_humidity", b"form_humidity", "form_temperature", b"form_temperature", "particles_03um", b"particles_03um", "particles_05um", b"particles_05um", "particles_100um", b"particles_100um", "particles_10um", b"particles_10um", "particles_25um", b"particles_25um", "particles_40um", b"particles_40um", "particles_50um", b"particles_50um", "particles_tps", b"particles_tps", "pm100_environmental", b"pm100_environmental", "pm100_standard", b"pm100_standard", "pm10_environmental", b"pm10_environmental", "pm10_standard", b"pm10_standard", "pm25_environmental", b"pm25_environmental", "pm25_standard", b"pm25_standard", "pm40_standard", b"pm40_standard", "pm_humidity", b"pm_humidity", "pm_nox_idx", b"pm_nox_idx", "pm_temperature", b"pm_temperature", "pm_voc_idx", b"pm_voc_idx"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__co2: _TypeAlias = _typing.Literal["co2"]  # noqa: Y015
    _WhichOneofArgType__co2: _TypeAlias = _typing.Literal["_co2", b"_co2"]  # noqa: Y015
    _WhichOneofReturnType__co2_humidity: _TypeAlias = _typing.Literal["co2_humidity"]  # noqa: Y015
    _WhichOneofArgType__co2_humidity: _TypeAlias = _typing.Literal["_co2_humidity", b"_co2_humidity"]  # noqa: Y015
    _WhichOneofReturnType__co2_temperature: _TypeAlias = _typing.Literal["co2_temperature"]  # noqa: Y015
    _WhichOneofArgType__co2_temperature: _TypeAlias = _typing.Literal["_co2_temperature", b"_co2_temperature"]  # noqa: Y015
    _WhichOneofReturnType__form_formaldehyde: _TypeAlias = _typing.Literal["form_formaldehyde"]  # noqa: Y015
    _WhichOneofArgType__form_formaldehyde: _TypeAlias = _typing.Literal["_form_formaldehyde", b"_form_formaldehyde"]  # noqa: Y015
    _WhichOneofReturnType__form_humidity: _TypeAlias = _typing.Literal["form_humidity"]  # noqa: Y015
    _WhichOneofArgType__form_humidity: _TypeAlias = _typing.Literal["_form_humidity", b"_form_humidity"]  # noqa: Y015
    _WhichOneofReturnType__form_temperature: _TypeAlias = _typing.Literal["form_temperature"]  # noqa: Y015
    _WhichOneofArgType__form_temperature: _TypeAlias = _typing.Literal["_form_temperature", b"_form_temperature"]  # noqa: Y015
    _WhichOneofReturnType__particles_03um: _TypeAlias = _typing.Literal["particles_03um"]  # noqa: Y015
    _WhichOneofArgType__particles_03um: _TypeAlias = _typing.Literal["_particles_03um", b"_particles_03um"]  # noqa: Y015
    _WhichOneofReturnType__particles_05um: _TypeAlias = _typing.Literal["particles_05um"]  # noqa: Y015
    _WhichOneofArgType__particles_05um: _TypeAlias = _typing.Literal["_particles_05um", b"_particles_05um"]  # noqa: Y015
    _WhichOneofReturnType__particles_100um: _TypeAlias = _typing.Literal["particles_100um"]  # noqa: Y015
    _WhichOneofArgType__particles_100um: _TypeAlias = _typing.Literal["_particles_100um", b"_particles_100um"]  # noqa: Y015
    _WhichOneofReturnType__particles_10um: _TypeAlias = _typing.Literal["particles_10um"]  # noqa: Y015
    _WhichOneofArgType__particles_10um: _TypeAlias = _typing.Literal["_particles_10um", b"_particles_10um"]  # noqa: Y015
    _WhichOneofReturnType__particles_25um: _TypeAlias = _typing.Literal["particles_25um"]  # noqa: Y015
    _WhichOneofArgType__particles_25um: _TypeAlias = _typing.Literal["_particles_25um", b"_particles_25um"]  # noqa: Y015
    _WhichOneofReturnType__particles_40um: _TypeAlias = _typing.Literal["particles_40um"]  # noqa: Y015
    _WhichOneofArgType__particles_40um: _TypeAlias = _typing.Literal["_particles_40um", b"_particles_40um"]  # noqa: Y015
    _WhichOneofReturnType__particles_50um: _TypeAlias = _typing.Literal["particles_50um"]  # noqa: Y015
    _WhichOneofArgType__particles_50um: _TypeAlias = _typing.Literal["_particles_50um", b"_particles_50um"]  # noqa: Y015
    _WhichOneofReturnType__particles_tps: _TypeAlias = _typing.Literal["particles_tps"]  # noqa: Y015
    _WhichOneofArgType__particles_tps: _TypeAlias = _typing.Literal["_particles_tps", b"_particles_tps"]  # noqa: Y015
    _WhichOneofReturnType__pm100_environmental: _TypeAlias = _typing.Literal["pm100_environmental"]  # noqa: Y015
    _WhichOneofArgType__pm100_environmental: _TypeAlias = _typing.Literal["_pm100_environmental", b"_pm100_environmental"]  # noqa: Y015
    _WhichOneofReturnType__pm100_standard: _TypeAlias = _typing.Literal["pm100_standard"]  # noqa: Y015
    _WhichOneofArgType__pm100_standard: _TypeAlias = _typing.Literal["_pm100_standard", b"_pm100_standard"]  # noqa: Y015
    _WhichOneofReturnType__pm10_environmental: _TypeAlias = _typing.Literal["pm10_environmental"]  # noqa: Y015
    _WhichOneofArgType__pm10_environmental: _TypeAlias = _typing.Literal["_pm10_environmental", b"_pm10_environmental"]  # noqa: Y015
    _WhichOneofReturnType__pm10_standard: _TypeAlias = _typing.Literal["pm10_standard"]  # noqa: Y015
    _WhichOneofArgType__pm10_standard: _TypeAlias = _typing.Literal["_pm10_standard", b"_pm10_standard"]  # noqa: Y015
    _WhichOneofReturnType__pm25_environmental: _TypeAlias = _typing.Literal["pm25_environmental"]  # noqa: Y015
    _WhichOneofArgType__pm25_environmental: _TypeAlias = _typing.Literal["_pm25_environmental", b"_pm25_environmental"]  # noqa: Y015
    _WhichOneofReturnType__pm25_standard: _TypeAlias = _typing.Literal["pm25_standard"]  # noqa: Y015
    _WhichOneofArgType__pm25_standard: _TypeAlias = _typing.Literal["_pm25_standard", b"_pm25_standard"]  # noqa: Y015
    _WhichOneofReturnType__pm40_standard: _TypeAlias = _typing.Literal["pm40_standard"]  # noqa: Y015
    _WhichOneofArgType__pm40_standard: _TypeAlias = _typing.Literal["_pm40_standard", b"_pm40_standard"]  # noqa: Y015
    _WhichOneofReturnType__pm_humidity: _TypeAlias = _typing.Literal["pm_humidity"]  # noqa: Y015
    _WhichOneofArgType__pm_humidity: _TypeAlias = _typing.Literal["_pm_humidity", b"_pm_humidity"]  # noqa: Y015
    _WhichOneofReturnType__pm_nox_idx: _TypeAlias = _typing.Literal["pm_nox_idx"]  # noqa: Y015
    _WhichOneofArgType__pm_nox_idx: _TypeAlias = _typing.Literal["_pm_nox_idx", b"_pm_nox_idx"]  # noqa: Y015
    _WhichOneofReturnType__pm_temperature: _TypeAlias = _typing.Literal["pm_temperature"]  # noqa: Y015
    _WhichOneofArgType__pm_temperature: _TypeAlias = _typing.Literal["_pm_temperature", b"_pm_temperature"]  # noqa: Y015
    _WhichOneofReturnType__pm_voc_idx: _TypeAlias = _typing.Literal["pm_voc_idx"]  # noqa: Y015
    _WhichOneofArgType__pm_voc_idx: _TypeAlias = _typing.Literal["_pm_voc_idx", b"_pm_voc_idx"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__co2) -> _WhichOneofReturnType__co2 | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__co2_humidity) -> _WhichOneofReturnType__co2_humidity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__co2_temperature) -> _WhichOneofReturnType__co2_temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__form_formaldehyde) -> _WhichOneofReturnType__form_formaldehyde | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__form_humidity) -> _WhichOneofReturnType__form_humidity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__form_temperature) -> _WhichOneofReturnType__form_temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_03um) -> _WhichOneofReturnType__particles_03um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_05um) -> _WhichOneofReturnType__particles_05um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_100um) -> _WhichOneofReturnType__particles_100um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_10um) -> _WhichOneofReturnType__particles_10um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_25um) -> _WhichOneofReturnType__particles_25um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_40um) -> _WhichOneofReturnType__particles_40um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_50um) -> _WhichOneofReturnType__particles_50um | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__particles_tps) -> _WhichOneofReturnType__particles_tps | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm100_environmental) -> _WhichOneofReturnType__pm100_environmental | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm100_standard) -> _WhichOneofReturnType__pm100_standard | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm10_environmental) -> _WhichOneofReturnType__pm10_environmental | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm10_standard) -> _WhichOneofReturnType__pm10_standard | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm25_environmental) -> _WhichOneofReturnType__pm25_environmental | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm25_standard) -> _WhichOneofReturnType__pm25_standard | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm40_standard) -> _WhichOneofReturnType__pm40_standard | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm_humidity) -> _WhichOneofReturnType__pm_humidity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm_nox_idx) -> _WhichOneofReturnType__pm_nox_idx | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm_temperature) -> _WhichOneofReturnType__pm_temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pm_voc_idx) -> _WhichOneofReturnType__pm_voc_idx | None: ...

Global___AirQualityMetrics: _TypeAlias = AirQualityMetrics  # noqa: Y015

@_typing.final
class LocalStats(_message.Message):
    """
    Local device mesh statistics
    """

    DESCRIPTOR: _descriptor.Descriptor

    UPTIME_SECONDS_FIELD_NUMBER: _builtins.int
    CHANNEL_UTILIZATION_FIELD_NUMBER: _builtins.int
    AIR_UTIL_TX_FIELD_NUMBER: _builtins.int
    NUM_PACKETS_TX_FIELD_NUMBER: _builtins.int
    NUM_PACKETS_RX_FIELD_NUMBER: _builtins.int
    NUM_PACKETS_RX_BAD_FIELD_NUMBER: _builtins.int
    NUM_ONLINE_NODES_FIELD_NUMBER: _builtins.int
    NUM_TOTAL_NODES_FIELD_NUMBER: _builtins.int
    NUM_RX_DUPE_FIELD_NUMBER: _builtins.int
    NUM_TX_RELAY_FIELD_NUMBER: _builtins.int
    NUM_TX_RELAY_CANCELED_FIELD_NUMBER: _builtins.int
    HEAP_TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    HEAP_FREE_BYTES_FIELD_NUMBER: _builtins.int
    NUM_TX_DROPPED_FIELD_NUMBER: _builtins.int
    NOISE_FLOOR_FIELD_NUMBER: _builtins.int
    uptime_seconds: _builtins.int
    """
    How long the device has been running since the last reboot (in seconds)
    """
    channel_utilization: _builtins.float
    """
    Utilization for the current channel, including well formed TX, RX and malformed RX (aka noise).
    """
    air_util_tx: _builtins.float
    """
    Percent of airtime for transmission used within the last hour.
    """
    num_packets_tx: _builtins.int
    """
    Number of packets sent
    """
    num_packets_rx: _builtins.int
    """
    Number of packets received (both good and bad)
    """
    num_packets_rx_bad: _builtins.int
    """
    Number of packets received that are malformed or violate the protocol
    """
    num_online_nodes: _builtins.int
    """
    Number of nodes online (in the past 2 hours)
    """
    num_total_nodes: _builtins.int
    """
    Number of nodes total
    """
    num_rx_dupe: _builtins.int
    """
    Number of received packets that were duplicates (due to multiple nodes relaying).
    If this number is high, there are nodes in the mesh relaying packets when it's unnecessary, for example due to the ROUTER/REPEATER role.
    """
    num_tx_relay: _builtins.int
    """
    Number of packets we transmitted that were a relay for others (not originating from ourselves).
    """
    num_tx_relay_canceled: _builtins.int
    """
    Number of times we canceled a packet to be relayed, because someone else did it before us.
    This will always be zero for ROUTERs/REPEATERs. If this number is high, some other node(s) is/are relaying faster than you.
    """
    heap_total_bytes: _builtins.int
    """
    Number of bytes used in the heap
    """
    heap_free_bytes: _builtins.int
    """
    Number of bytes free in the heap
    """
    num_tx_dropped: _builtins.int
    """
    Number of packets that were dropped because the transmit queue was full.
    """
    noise_floor: _builtins.int
    """
    Noise floor value measured in dBm
    """
    def __init__(
        self,
        *,
        uptime_seconds: _builtins.int = ...,
        channel_utilization: _builtins.float = ...,
        air_util_tx: _builtins.float = ...,
        num_packets_tx: _builtins.int = ...,
        num_packets_rx: _builtins.int = ...,
        num_packets_rx_bad: _builtins.int = ...,
        num_online_nodes: _builtins.int = ...,
        num_total_nodes: _builtins.int = ...,
        num_rx_dupe: _builtins.int = ...,
        num_tx_relay: _builtins.int = ...,
        num_tx_relay_canceled: _builtins.int = ...,
        heap_total_bytes: _builtins.int = ...,
        heap_free_bytes: _builtins.int = ...,
        num_tx_dropped: _builtins.int = ...,
        noise_floor: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["air_util_tx", b"air_util_tx", "channel_utilization", b"channel_utilization", "heap_free_bytes", b"heap_free_bytes", "heap_total_bytes", b"heap_total_bytes", "noise_floor", b"noise_floor", "num_online_nodes", b"num_online_nodes", "num_packets_rx", b"num_packets_rx", "num_packets_rx_bad", b"num_packets_rx_bad", "num_packets_tx", b"num_packets_tx", "num_rx_dupe", b"num_rx_dupe", "num_total_nodes", b"num_total_nodes", "num_tx_dropped", b"num_tx_dropped", "num_tx_relay", b"num_tx_relay", "num_tx_relay_canceled", b"num_tx_relay_canceled", "uptime_seconds", b"uptime_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocalStats: _TypeAlias = LocalStats  # noqa: Y015

@_typing.final
class TrafficManagementStats(_message.Message):
    """
    Traffic management statistics for mesh network optimization
    """

    DESCRIPTOR: _descriptor.Descriptor

    PACKETS_INSPECTED_FIELD_NUMBER: _builtins.int
    POSITION_DEDUP_DROPS_FIELD_NUMBER: _builtins.int
    NODEINFO_CACHE_HITS_FIELD_NUMBER: _builtins.int
    RATE_LIMIT_DROPS_FIELD_NUMBER: _builtins.int
    UNKNOWN_PACKET_DROPS_FIELD_NUMBER: _builtins.int
    HOP_EXHAUSTED_PACKETS_FIELD_NUMBER: _builtins.int
    ROUTER_HOPS_PRESERVED_FIELD_NUMBER: _builtins.int
    packets_inspected: _builtins.int
    """
    Total number of packets inspected by traffic management
    """
    position_dedup_drops: _builtins.int
    """
    Number of position packets dropped due to deduplication
    """
    nodeinfo_cache_hits: _builtins.int
    """
    Number of NodeInfo requests answered from cache
    """
    rate_limit_drops: _builtins.int
    """
    Number of packets dropped due to rate limiting
    """
    unknown_packet_drops: _builtins.int
    """
    Number of unknown/undecryptable packets dropped
    """
    hop_exhausted_packets: _builtins.int
    """
    Number of packets with hop_limit exhausted for local-only broadcast
    """
    router_hops_preserved: _builtins.int
    """
    Number of times router hop preservation was applied
    """
    def __init__(
        self,
        *,
        packets_inspected: _builtins.int = ...,
        position_dedup_drops: _builtins.int = ...,
        nodeinfo_cache_hits: _builtins.int = ...,
        rate_limit_drops: _builtins.int = ...,
        unknown_packet_drops: _builtins.int = ...,
        hop_exhausted_packets: _builtins.int = ...,
        router_hops_preserved: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hop_exhausted_packets", b"hop_exhausted_packets", "nodeinfo_cache_hits", b"nodeinfo_cache_hits", "packets_inspected", b"packets_inspected", "position_dedup_drops", b"position_dedup_drops", "rate_limit_drops", b"rate_limit_drops", "router_hops_preserved", b"router_hops_preserved", "unknown_packet_drops", b"unknown_packet_drops"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TrafficManagementStats: _TypeAlias = TrafficManagementStats  # noqa: Y015

@_typing.final
class HealthMetrics(_message.Message):
    """
    Health telemetry metrics
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEART_BPM_FIELD_NUMBER: _builtins.int
    SPO2_FIELD_NUMBER: _builtins.int
    TEMPERATURE_FIELD_NUMBER: _builtins.int
    heart_bpm: _builtins.int
    """
    Heart rate (beats per minute)
    """
    spO2: _builtins.int
    """
    SpO2 (blood oxygen saturation) level
    """
    temperature: _builtins.float
    """
    Body temperature in degrees Celsius
    """
    def __init__(
        self,
        *,
        heart_bpm: _builtins.int | None = ...,
        spO2: _builtins.int | None = ...,
        temperature: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_heart_bpm", b"_heart_bpm", "_spO2", b"_spO2", "_temperature", b"_temperature", "heart_bpm", b"heart_bpm", "spO2", b"spO2", "temperature", b"temperature"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_heart_bpm", b"_heart_bpm", "_spO2", b"_spO2", "_temperature", b"_temperature", "heart_bpm", b"heart_bpm", "spO2", b"spO2", "temperature", b"temperature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__heart_bpm: _TypeAlias = _typing.Literal["heart_bpm"]  # noqa: Y015
    _WhichOneofArgType__heart_bpm: _TypeAlias = _typing.Literal["_heart_bpm", b"_heart_bpm"]  # noqa: Y015
    _WhichOneofReturnType__spO2: _TypeAlias = _typing.Literal["spO2"]  # noqa: Y015
    _WhichOneofArgType__spO2: _TypeAlias = _typing.Literal["_spO2", b"_spO2"]  # noqa: Y015
    _WhichOneofReturnType__temperature: _TypeAlias = _typing.Literal["temperature"]  # noqa: Y015
    _WhichOneofArgType__temperature: _TypeAlias = _typing.Literal["_temperature", b"_temperature"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__heart_bpm) -> _WhichOneofReturnType__heart_bpm | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__spO2) -> _WhichOneofReturnType__spO2 | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__temperature) -> _WhichOneofReturnType__temperature | None: ...

Global___HealthMetrics: _TypeAlias = HealthMetrics  # noqa: Y015

@_typing.final
class HostMetrics(_message.Message):
    """
    Linux host metrics
    """

    DESCRIPTOR: _descriptor.Descriptor

    UPTIME_SECONDS_FIELD_NUMBER: _builtins.int
    FREEMEM_BYTES_FIELD_NUMBER: _builtins.int
    DISKFREE1_BYTES_FIELD_NUMBER: _builtins.int
    DISKFREE2_BYTES_FIELD_NUMBER: _builtins.int
    DISKFREE3_BYTES_FIELD_NUMBER: _builtins.int
    LOAD1_FIELD_NUMBER: _builtins.int
    LOAD5_FIELD_NUMBER: _builtins.int
    LOAD15_FIELD_NUMBER: _builtins.int
    USER_STRING_FIELD_NUMBER: _builtins.int
    uptime_seconds: _builtins.int
    """
    Host system uptime
    """
    freemem_bytes: _builtins.int
    """
    Host system free memory
    """
    diskfree1_bytes: _builtins.int
    """
    Host system disk space free for /
    """
    diskfree2_bytes: _builtins.int
    """
    Secondary system disk space free
    """
    diskfree3_bytes: _builtins.int
    """
    Tertiary disk space free
    """
    load1: _builtins.int
    """
    Host system one minute load in 1/100ths
    """
    load5: _builtins.int
    """
    Host system five minute load  in 1/100ths
    """
    load15: _builtins.int
    """
    Host system fifteen minute load  in 1/100ths
    """
    user_string: _builtins.str
    """
    Optional User-provided string for arbitrary host system information
    that doesn't make sense as a dedicated entry.
    """
    def __init__(
        self,
        *,
        uptime_seconds: _builtins.int = ...,
        freemem_bytes: _builtins.int = ...,
        diskfree1_bytes: _builtins.int = ...,
        diskfree2_bytes: _builtins.int | None = ...,
        diskfree3_bytes: _builtins.int | None = ...,
        load1: _builtins.int = ...,
        load5: _builtins.int = ...,
        load15: _builtins.int = ...,
        user_string: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_diskfree2_bytes", b"_diskfree2_bytes", "_diskfree3_bytes", b"_diskfree3_bytes", "_user_string", b"_user_string", "diskfree2_bytes", b"diskfree2_bytes", "diskfree3_bytes", b"diskfree3_bytes", "user_string", b"user_string"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_diskfree2_bytes", b"_diskfree2_bytes", "_diskfree3_bytes", b"_diskfree3_bytes", "_user_string", b"_user_string", "diskfree1_bytes", b"diskfree1_bytes", "diskfree2_bytes", b"diskfree2_bytes", "diskfree3_bytes", b"diskfree3_bytes", "freemem_bytes", b"freemem_bytes", "load1", b"load1", "load15", b"load15", "load5", b"load5", "uptime_seconds", b"uptime_seconds", "user_string", b"user_string"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__diskfree2_bytes: _TypeAlias = _typing.Literal["diskfree2_bytes"]  # noqa: Y015
    _WhichOneofArgType__diskfree2_bytes: _TypeAlias = _typing.Literal["_diskfree2_bytes", b"_diskfree2_bytes"]  # noqa: Y015
    _WhichOneofReturnType__diskfree3_bytes: _TypeAlias = _typing.Literal["diskfree3_bytes"]  # noqa: Y015
    _WhichOneofArgType__diskfree3_bytes: _TypeAlias = _typing.Literal["_diskfree3_bytes", b"_diskfree3_bytes"]  # noqa: Y015
    _WhichOneofReturnType__user_string: _TypeAlias = _typing.Literal["user_string"]  # noqa: Y015
    _WhichOneofArgType__user_string: _TypeAlias = _typing.Literal["_user_string", b"_user_string"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__diskfree2_bytes) -> _WhichOneofReturnType__diskfree2_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__diskfree3_bytes) -> _WhichOneofReturnType__diskfree3_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__user_string) -> _WhichOneofReturnType__user_string | None: ...

Global___HostMetrics: _TypeAlias = HostMetrics  # noqa: Y015

@_typing.final
class Telemetry(_message.Message):
    """
    Types of Measurements the telemetry module is equipped to handle
    """

    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    DEVICE_METRICS_FIELD_NUMBER: _builtins.int
    ENVIRONMENT_METRICS_FIELD_NUMBER: _builtins.int
    AIR_QUALITY_METRICS_FIELD_NUMBER: _builtins.int
    POWER_METRICS_FIELD_NUMBER: _builtins.int
    LOCAL_STATS_FIELD_NUMBER: _builtins.int
    HEALTH_METRICS_FIELD_NUMBER: _builtins.int
    HOST_METRICS_FIELD_NUMBER: _builtins.int
    TRAFFIC_MANAGEMENT_STATS_FIELD_NUMBER: _builtins.int
    time: _builtins.int
    """
    Seconds since 1970 - or 0 for unknown/unset
    """
    @_builtins.property
    def device_metrics(self) -> Global___DeviceMetrics:
        """
        Key native device metrics such as battery level
        """

    @_builtins.property
    def environment_metrics(self) -> Global___EnvironmentMetrics:
        """
        Weather station or other environmental metrics
        """

    @_builtins.property
    def air_quality_metrics(self) -> Global___AirQualityMetrics:
        """
        Air quality metrics
        """

    @_builtins.property
    def power_metrics(self) -> Global___PowerMetrics:
        """
        Power Metrics
        """

    @_builtins.property
    def local_stats(self) -> Global___LocalStats:
        """
        Local device mesh statistics
        """

    @_builtins.property
    def health_metrics(self) -> Global___HealthMetrics:
        """
        Health telemetry metrics
        """

    @_builtins.property
    def host_metrics(self) -> Global___HostMetrics:
        """
        Linux host metrics
        """

    @_builtins.property
    def traffic_management_stats(self) -> Global___TrafficManagementStats:
        """
        Traffic management statistics
        """

    def __init__(
        self,
        *,
        time: _builtins.int = ...,
        device_metrics: Global___DeviceMetrics | None = ...,
        environment_metrics: Global___EnvironmentMetrics | None = ...,
        air_quality_metrics: Global___AirQualityMetrics | None = ...,
        power_metrics: Global___PowerMetrics | None = ...,
        local_stats: Global___LocalStats | None = ...,
        health_metrics: Global___HealthMetrics | None = ...,
        host_metrics: Global___HostMetrics | None = ...,
        traffic_management_stats: Global___TrafficManagementStats | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["air_quality_metrics", b"air_quality_metrics", "device_metrics", b"device_metrics", "environment_metrics", b"environment_metrics", "health_metrics", b"health_metrics", "host_metrics", b"host_metrics", "local_stats", b"local_stats", "power_metrics", b"power_metrics", "traffic_management_stats", b"traffic_management_stats", "variant", b"variant"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["air_quality_metrics", b"air_quality_metrics", "device_metrics", b"device_metrics", "environment_metrics", b"environment_metrics", "health_metrics", b"health_metrics", "host_metrics", b"host_metrics", "local_stats", b"local_stats", "power_metrics", b"power_metrics", "time", b"time", "traffic_management_stats", b"traffic_management_stats", "variant", b"variant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_variant: _TypeAlias = _typing.Literal["device_metrics", "environment_metrics", "air_quality_metrics", "power_metrics", "local_stats", "health_metrics", "host_metrics", "traffic_management_stats"]  # noqa: Y015
    _WhichOneofArgType_variant: _TypeAlias = _typing.Literal["variant", b"variant"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_variant) -> _WhichOneofReturnType_variant | None: ...

Global___Telemetry: _TypeAlias = Telemetry  # noqa: Y015

@_typing.final
class Nau7802Config(_message.Message):
    """
    NAU7802 Telemetry configuration, for saving to flash
    """

    DESCRIPTOR: _descriptor.Descriptor

    ZEROOFFSET_FIELD_NUMBER: _builtins.int
    CALIBRATIONFACTOR_FIELD_NUMBER: _builtins.int
    zeroOffset: _builtins.int
    """
    The offset setting for the NAU7802
    """
    calibrationFactor: _builtins.float
    """
    The calibration factor for the NAU7802
    """
    def __init__(
        self,
        *,
        zeroOffset: _builtins.int = ...,
        calibrationFactor: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["calibrationFactor", b"calibrationFactor", "zeroOffset", b"zeroOffset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Nau7802Config: _TypeAlias = Nau7802Config  # noqa: Y015

@_typing.final
class SEN5XState(_message.Message):
    """
    SEN5X State, for saving to flash
    """

    DESCRIPTOR: _descriptor.Descriptor

    LAST_CLEANING_TIME_FIELD_NUMBER: _builtins.int
    LAST_CLEANING_VALID_FIELD_NUMBER: _builtins.int
    ONE_SHOT_MODE_FIELD_NUMBER: _builtins.int
    VOC_STATE_TIME_FIELD_NUMBER: _builtins.int
    VOC_STATE_VALID_FIELD_NUMBER: _builtins.int
    VOC_STATE_ARRAY_FIELD_NUMBER: _builtins.int
    last_cleaning_time: _builtins.int
    """
    Last cleaning time for SEN5X
    """
    last_cleaning_valid: _builtins.bool
    """
    Last cleaning time for SEN5X - valid flag
    """
    one_shot_mode: _builtins.bool
    """
    Config flag for one-shot mode (see admin.proto)
    """
    voc_state_time: _builtins.int
    """
    Last VOC state time for SEN55
    """
    voc_state_valid: _builtins.bool
    """
    Last VOC state validity flag for SEN55
    """
    voc_state_array: _builtins.int
    """
    VOC state array (8x uint8t) for SEN55
    """
    def __init__(
        self,
        *,
        last_cleaning_time: _builtins.int = ...,
        last_cleaning_valid: _builtins.bool = ...,
        one_shot_mode: _builtins.bool = ...,
        voc_state_time: _builtins.int | None = ...,
        voc_state_valid: _builtins.bool | None = ...,
        voc_state_array: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_voc_state_array", b"_voc_state_array", "_voc_state_time", b"_voc_state_time", "_voc_state_valid", b"_voc_state_valid", "voc_state_array", b"voc_state_array", "voc_state_time", b"voc_state_time", "voc_state_valid", b"voc_state_valid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_voc_state_array", b"_voc_state_array", "_voc_state_time", b"_voc_state_time", "_voc_state_valid", b"_voc_state_valid", "last_cleaning_time", b"last_cleaning_time", "last_cleaning_valid", b"last_cleaning_valid", "one_shot_mode", b"one_shot_mode", "voc_state_array", b"voc_state_array", "voc_state_time", b"voc_state_time", "voc_state_valid", b"voc_state_valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__voc_state_array: _TypeAlias = _typing.Literal["voc_state_array"]  # noqa: Y015
    _WhichOneofArgType__voc_state_array: _TypeAlias = _typing.Literal["_voc_state_array", b"_voc_state_array"]  # noqa: Y015
    _WhichOneofReturnType__voc_state_time: _TypeAlias = _typing.Literal["voc_state_time"]  # noqa: Y015
    _WhichOneofArgType__voc_state_time: _TypeAlias = _typing.Literal["_voc_state_time", b"_voc_state_time"]  # noqa: Y015
    _WhichOneofReturnType__voc_state_valid: _TypeAlias = _typing.Literal["voc_state_valid"]  # noqa: Y015
    _WhichOneofArgType__voc_state_valid: _TypeAlias = _typing.Literal["_voc_state_valid", b"_voc_state_valid"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voc_state_array) -> _WhichOneofReturnType__voc_state_array | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voc_state_time) -> _WhichOneofReturnType__voc_state_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voc_state_valid) -> _WhichOneofReturnType__voc_state_valid | None: ...

Global___SEN5XState: _TypeAlias = SEN5XState  # noqa: Y015
