"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class XModem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Control:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ControlEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[XModem._Control.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NUL: XModem._Control.ValueType  # 0
        SOH: XModem._Control.ValueType  # 1
        STX: XModem._Control.ValueType  # 2
        EOT: XModem._Control.ValueType  # 4
        ACK: XModem._Control.ValueType  # 6
        NAK: XModem._Control.ValueType  # 21
        CAN: XModem._Control.ValueType  # 24
        CTRLZ: XModem._Control.ValueType  # 26

    class Control(_Control, metaclass=_ControlEnumTypeWrapper): ...
    NUL: XModem.Control.ValueType  # 0
    SOH: XModem.Control.ValueType  # 1
    STX: XModem.Control.ValueType  # 2
    EOT: XModem.Control.ValueType  # 4
    ACK: XModem.Control.ValueType  # 6
    NAK: XModem.Control.ValueType  # 21
    CAN: XModem.Control.ValueType  # 24
    CTRLZ: XModem.Control.ValueType  # 26

    CONTROL_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    CRC16_FIELD_NUMBER: _builtins.int
    BUFFER_FIELD_NUMBER: _builtins.int
    control: Global___XModem.Control.ValueType
    seq: _builtins.int
    crc16: _builtins.int
    buffer: _builtins.bytes
    def __init__(
        self,
        *,
        control: Global___XModem.Control.ValueType = ...,
        seq: _builtins.int = ...,
        crc16: _builtins.int = ...,
        buffer: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["buffer", b"buffer", "control", b"control", "crc16", b"crc16", "seq", b"seq"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___XModem: _TypeAlias = XModem  # noqa: Y015
